- Makefile
- ci/azure-pipelines.yml
- ci/version_var.sh
- cmd/vc-rest/go.mod
- cmd/vc-rest/startcmd/start.go
- images/vc-rest/Dockerfile
- pkg/restapi/vc/controller.go
- pkg/restapi/vc/controller_test.go
- pkg/restapi/vc/operation/operations.go
closes #11 
A Docker image for a VC server can now be published.
Added a line of output to indicate the server is running.
Fixed an incorrectly named package.
Fixed an incorrect comment.
> feat: VC Docker Image

- cmd/vc-rest/go.mod
- cmd/vc-rest/go.sum
- cmd/vc-rest/startcmd/start.go
- go.mod
- go.sum
- pkg/internal/mock/client.go
- pkg/restapi/vc/controller.go
- pkg/restapi/vc/controller_test.go
- pkg/restapi/vc/operation/models.go
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- pkg/restapi/vc/operation/profile_test.go
> feat: Store VC and retrieve VC using edge client

- go.mod
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- test/bdd/fixtures/edv-rest/.env
- test/bdd/pkg/vc/vc_steps.go
closes #66
VC-service now encodes document IDs to conform with the new version of the EDV server.
Updated the BDD tests to use the latest EDV image.
Fixed some incorrect error messages in the BDD-tests.
Fixed a few places in the retrieve document handler where errors occurred and the function didn't return after writing the error response.
> feat: Use base58 encoded 128-bit values for document IDs

- cmd/vc-rest/go.mod
- cmd/vc-rest/go.sum
- cmd/vc-rest/startcmd/start.go
- cmd/vc-rest/startcmd/start_test.go
- go.mod
- go.sum
- pkg/internal/mock/edv/client.go
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- test/bdd/fixtures/edv-rest/.env
- test/bdd/go.sum
- test/bdd/pkg/vc/vc_steps.go
- Many of the operations unit tests were using a mocked KMS when they could have used a real one - those have been updated to use real in-memory KMSs now.
- Added shorthand flags for the Bloc domain, external URL host, and universal resolver URL flags.
- Some other minor refactoring and fixes
closes #61
> feat: Encrypt documents sent to EDV

- pkg/doc/vc/crypto/crypto.go
- pkg/doc/vc/crypto/crypto_test.go
- pkg/doc/vc/profile/profile.go
- pkg/doc/vc/profile/profile_test.go
- pkg/restapi/vc/operation/models.go
- pkg/restapi/vc/operation/operations.go
- test/bdd/features/vc_e2e_api.feature
- test/bdd/pkg/context/context.go
- test/bdd/pkg/vc/vc_steps.go
When creating credentials, we should be able to sign using jws field in the Linked Data Signature.
Also, add test to check verifiable presentation when signed using either 'JWT' or 'ProofValue' signature holder.
Closes #100
> feat: Support JWS proof format

- pkg/restapi/vc/controller_test.go
- pkg/restapi/vc/operation/models.go
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- test/bdd/pkg/verifier/verifier_steps.go
- Add new endpoint https://w3c-ccg.github.io/vc-verifier-http-api/#/internal/verifyCredential and point it to existing /verifications code
- Deprecate exising /verifications API
- Update BDD tests to use new endpoint
closes #149 
> feat: CredentialsVerification API

- cmd/vc-rest/startcmd/start.go
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
Add a combined mode that allows the service to be deployed as both
an issuer and verifier.
Closes: #158
> feat: combined mode

- pkg/restapi/vc/operation/models.go
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- test/bdd/features/issuer_e2e_api.feature
- test/bdd/pkg/issuer/issuer_steps.go
> refactor: Issue Credential API - Use issuerDID as default signing DID when request Opts is empty

- Makefile
- cmd/vc-rest/go.mod
- cmd/vc-rest/go.sum
- cmd/vc-rest/startcmd/start.go
- go.mod
- go.sum
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- scripts/prepare-test-verifiables.js
- scripts/prepare_test_verifiables.sh
- scripts/uniregistrar-create-dids.js
- scripts/uniregistrar_create_dids.sh
- test/bdd/bddtests_test.go
- test/bdd/features/vc_e2e_api.feature
- test/bdd/features/verifier_e2e_api.feature
- test/bdd/fixtures/universalresolver/config.json
- test/bdd/fixtures/universalresolver/docker-compose.yml
- test/bdd/go.mod
- test/bdd/go.sum
- test/bdd/pkg/bddutil/util.go
- test/bdd/pkg/context/context.go
- test/bdd/pkg/issuer/issuer_steps.go
- test/bdd/pkg/vc/vc_steps.go
- test/bdd/pkg/verifier/verifier_steps.go
- test/bdd/testdata/profile_request_template.json
- test/bdd/testdata/transmute_vc.json
- test/bdd/testdata/transmute_vp.json
- test/bdd/testdata/university_degree_credential.json
- added interop tests for verifying transmute verifiable credentials and
veriable presentations issued by `vc.transmute.world`
- added make target `prepare-test-verifiables` to generate VCs and VPs
from external API endpoints.
- closes #187
> feat: interop tests with transmute VCs & VPs

- Makefile
- cmd/vc-rest/go.mod
- cmd/vc-rest/go.sum
- go.mod
- go.sum
- scripts/check_integration.sh
- scripts/create-element-did.js
- test/bdd/bddtests_test.go
- test/bdd/features/thirdparty_verifier_e2e.feature
- test/bdd/features/verifier_e2e_api.feature
- test/bdd/go.mod
- test/bdd/go.sum
- test/bdd/pkg/bddutil/util.go
- test/bdd/pkg/issuer/issuer_steps.go
- test/bdd/pkg/vc/vc_steps.go
- test/bdd/pkg/verifier/verifier_steps.go
- added new bdd test target `bdd-interop-test` to verify our verifiables
using third party verifiers to test interoperability. This target can be
used in future to test bdd scenarios involving third party systems.
- this target is not part of CI
- this target will be part of nightly/daily build once stable
- pending work on this test can be found in #229
- closes #109
> feat: bdd interop tests to verify VCs & VPs using third party verifiers

- pkg/doc/vc/crypto/crypto.go
- pkg/doc/vc/crypto/crypto_test.go
- pkg/doc/vc/profile/profile.go
- pkg/doc/vc/status/csl/csl.go
- pkg/restapi/vc/operation/models.go
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- test/bdd/pkg/issuer/issuer_steps.go
- test/bdd/pkg/vc/vc_steps.go
- credential issuer to be dynamically populated as per #251
- issue credential assertion method changed from DID to DID Verification
Key ID
- added purpose in issue credential options
- added putpose in compose credential options
- refactored crypto sign credential to accept dynamic opts
- updated bdd tests to use options & profile.overwriteIssuer
- Closes #239
- Closes #251
TODO:(Will be part of next PR) Avoid overriding of Credential issuer & proof options during
crdential status update
> feat: issuer override and verification method for issue and compose

- pkg/doc/vc/crypto/crypto.go
- pkg/doc/vc/crypto/crypto_test.go
- pkg/doc/vc/status/csl/csl.go
- pkg/doc/vc/status/csl/csl_test.go
- pkg/restapi/vc/operation/models.go
- pkg/restapi/vc/operation/operations.go
- pkg/restapi/vc/operation/operations_test.go
- test/bdd/features/thirdparty_verifier_e2e.feature
- test/bdd/pkg/vc/vc_steps.go
- changed vc status update logic to preserve issuer and proof options
from original VC
- added created proof options support for issue and compose credential
- added bdd test step for creating and veifying VCs with 'did:key'
- Closes #273
- Closes #291
- Closes #269
- Closes #255
> feat: update vc status  refactor and new signing options

- cmd/did-rest/go.mod
- cmd/did-rest/go.sum
- cmd/vc-rest/go.mod
- cmd/vc-rest/go.sum
- go.mod
- go.sum
- pkg/doc/vc/profile/profile.go
- pkg/doc/vc/profile/verifier/profile.go
- pkg/doc/vc/status/csl/csl.go
- pkg/doc/vc/status/csl/csl_test.go
- pkg/restapi/internal/common/vcutil/vcutil.go
- test/bdd/fixtures/edv-rest/.env
- test/bdd/go.mod
- test/bdd/go.sum
- Updates edge-core dependency (includes trustbloc/edge-core#52, trustbloc/edge-core#55)
- updates edv dependency and Docker image (also includes the above edge-core updates)
> chore: Update edv and edge-core versions

- .golangci.yml
- cmd/did-rest/go.mod
- cmd/did-rest/go.sum
- cmd/vc-rest/go.mod
- cmd/vc-rest/go.sum
- go.mod
- go.sum
- pkg/restapi/issuer/operation/operations_test.go
- test/bdd/go.mod
- test/bdd/go.sum
- New edge-core version includes trustbloc/edge-core#64
> chore: Update edge-core dependency, use mock logger

- cmd/vc-rest/startcmd/start.go
- cmd/vc-rest/startcmd/start_test.go
- Removed warning that would get logged when using the same database for the non-KMS provider and KMS provider. The warning was effectively assuming that the database used for the non-KMS provider will also host the EDV, which doesn't make sense.
- Refactored the createKMS method to only take in the provider it needs, instead of taking in the whole struct. This makes what the method actually needs more clear.
> fix: Removed incorrect warning, minor code refactor

- pkg/internal/cryptosetup/cryptosetup.go
- Fixes an issue where the  JWE encrypter is missing the key ID when reusing the existing local key ID from storage.
> fix: Missing key ID

- cmd/comparator-rest/docs/openapi.yaml
- cmd/vault-server/docs/openapi.yaml
Tidying up the OpenAPI specs for the Vault Server and the Comparator.
TODO: convert the specs to swagger 2.0 format (followup)
* add: more descriptions
* del: Scope.targetAttr from Scope The Vault Server does not
support authorization at such a fine-grained level.
* add: enum values to Scope.actions
* add: Scope.vaultID
* add: DocQuery.vaultID
* add: Config.authKeyURL
* add: generic error messages and status codes
* add: DocumentMetadata.encKeyURI
* fix: Authorization.scope was an array, now a single element
> docs: openapi specs for vault-server and comparator

- pkg/restapi/csh/operation/operations.go
- pkg/restapi/csh/operation/operations_test.go
Otherwise creating child zcaps fails when setting the parent zcap's ID in the capability chain.
> fix: confidential-storage-hub - make profile.ID a URN

- cmd/comparator-rest/docs/openapi.yaml
- pkg/client/comparator/models/scope.go
- pkg/client/vault/client.go
- pkg/restapi/comparator/operation/authz.go
- pkg/restapi/comparator/operation/compare.go
- pkg/restapi/comparator/operation/models/scope.go
- pkg/restapi/vault/client.go
- pkg/restapi/vault/client_test.go
- pkg/restapi/vault/operation/openapi.go
- pkg/restapi/vault/operation/operations_test.go
- test/bdd/fixtures/vault-server/docker-compose.yml
- test/bdd/go.mod
- test/bdd/go.sum
- test/bdd/pkg/comparator/comparator_steps.go
- test/bdd/pkg/vault/vault_steps.go
* vault-server: the EDV StructuredDocument model was not being used to  save documents
* comparator: added DocAttrPath so that the client can authorize comparisons against specific portions of the document. TODO encode this path into the zcap token.
> fix: vault-server, comparator

- pkg/restapi/holder/controller_test.go
- pkg/restapi/holder/operation/models.go
- pkg/restapi/holder/operation/openapi.go
- pkg/restapi/holder/operation/operations.go
- pkg/restapi/holder/operation/operations_test.go
> feat: add deriveCredential for holder

- pkg/restapi/holder/operation/models.go
- pkg/restapi/holder/operation/operations.go
- pkg/restapi/holder/operation/operations_test.go
- Case 1: No option provided - generate nonce.
- Case 2: Option provided with empty string - use empty.
- Case 3: option provided with nonce - use nonce from option.
> feat: handle nonce cases

- cmd/vc-rest/startcmd/start.go
- cmd/vc-rest/startcmd/start_test.go
Set `VC_REST_CONTEXT_ENABLE_REMOTE ` env variable to `true` to enable fetching JSON-LD contexts from the network.
> feat: add option to enable remote contexts fetching

- cmd/vc-rest/startcmd/start.go
- pkg/restapi/v1/issuer/controller_test.go
- pkg/restapi/v1/mw/api_key_auth.go
- pkg/restapi/v1/mw/api_key_auth_test.go
- pkg/restapi/v1/util/auth.go
- pkg/restapi/v1/verifier/controller.go
- pkg/restapi/v1/verifier/controller_test.go
- pkg/restapi/v1/verifier/testdata/create_profile_data.json
- scripts/generate_test_keys.sh
- test/bdd/features/issuer_profile_v1_api.feature
- test/bdd/features/verifier_profile_v1_api.feature
- test/bdd/fixtures/.env
- test/bdd/fixtures/docker-compose.yml
- test/bdd/fixtures/hydra-config/hydra_configure.sh
- test/bdd/fixtures/mysql-config/mysql_config.sql
- test/bdd/fixtures/oathkeeper-config/config.yaml
- test/bdd/fixtures/oathkeeper-config/rules/resource-server.json
- test/bdd/go.mod
- test/bdd/go.sum
- test/bdd/pkg/bddutil/util.go
- test/bdd/pkg/v1/issuer/issuer_steps.go
- test/bdd/pkg/v1/verifier/verifer_steps.go
> feat: OIDC client credential authorization

- component/oidc/vp/requestobjectstore.go
- component/oidc/vp/requestobjectstore_test.go
- test/bdd/fixtures/docker-compose.yml
- test/bdd/fixtures/nginx-config/data/.gitignore
- test/bdd/fixtures/nginx-config/nginx.conf
Linked ticket: https://github.com/trustbloc/vcs/issues/754
> feat: Support OpenID4VP - Mocked public store for request object

- test/bdd/features/vc_dev_api.feature
- test/bdd/pkg/vc-devapi/vc_devapi_steps.go
Test for this endpoint does not make sense, as it requires first to create that credentials, and this logic already covered in https://github.com/trustbloc/vcs/blob/7275a8303d1c0be9c2016963c16559bb2df8b3d0/test/bdd/pkg/v1/oidc4vp/oidc4vp.go#L118 for both creating and requesting this endpoint
> test: drop useless test for object-store

- cmd/vc-rest/startcmd/start.go
- pkg/doc/vc/crypto/crypto.go
- pkg/doc/vc/crypto/crypto_test.go
- pkg/doc/vc/signer.go
- pkg/restapi/v1/issuer/controller.go
- pkg/restapi/v1/issuer/controller_test.go
- pkg/service/credentialstatus/credentialstatus_service.go
- pkg/service/credentialstatus/credentialstatus_service_test.go
- pkg/service/didconfiguration/didconfiguration_service.go
- pkg/service/didconfiguration/didconfiguration_service_test.go
- pkg/service/issuecredential/issuecredential_service.go
- pkg/service/issuecredential/issuecredential_service_test.go
- pkg/service/verifycredential/revocation/revocation_service.go
- pkg/storage/mongodbprovider/csl.go
- test/bdd/features/vc_v1_e2e_api.feature
- test/bdd/fixtures/profile/profiles.json
- test/bdd/pkg/v1/model/model.go
- test/bdd/pkg/v1/vc/credential.go
- test/bdd/pkg/v1/vc/stress_steps.go
- test/bdd/pkg/v1/vc/vc_steps.go
> feat: Credential Status API - update vc status

- component/event/bus_test.go
- component/event/event.go
- component/event/publisher_test.go
- component/event/subscriber_test.go
- pkg/event/spi/spi.go
- pkg/event/spi/spi_test.go
- pkg/service/oidc4ci/models.go
- pkg/service/oidc4ci/oidc4ci_service.go
- pkg/service/oidc4vp/oidc4vp_service.go
- pkg/storage/mongodb/requestobjectstore/request_object_store_test.go
- test/bdd/pkg/v1/oidc4vc/oidc4vp.go
- test/bdd/pkg/v1/oidc4vp/oidc4vp.go
Add optional fields to event and adjust sending and receiving events. Transaction ID has been moved from data payload to event level.
Closes #970
> feat: Add optional fields to event

- pkg/event/spi/spi.go
Change event payload type to []byte; use camel case for JSON fields
Closes #996
> chore: Modify event payload type; camel case for JSON fields

- cmd/vc-rest/startcmd/params.go
- cmd/vc-rest/startcmd/start.go
- cmd/vc-rest/startcmd/start_test.go
- component/event/event.go
- component/event/go.mod
- component/event/go.sum
- component/oidc/vp/requestobjectstore.go
- component/oidc/vp/requestobjectstore_test.go
- pkg/service/oidc4ci/oidc4ci_service.go
- pkg/service/oidc4ci/oidc4ci_service_exchange_code_test.go
- pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go
- pkg/service/oidc4ci/oidc4ci_service_store_auth_code_test.go
- pkg/service/oidc4ci/oidc4ci_service_test.go
- pkg/service/oidc4vp/oidc4vp_service.go
- pkg/service/oidc4vp/oidc4vp_service_test.go
The issuer and verifier event topic names are now configurable. By default they are 'vcs-issuer' and 'vcs-verifier' respectively.
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
> chore: Configure event topics

- cmd/vc-rest/go.mod
- cmd/vc-rest/go.sum
- component/credentialstatus/go.mod
- component/credentialstatus/go.sum
- component/event/go.mod
- component/event/go.sum
- component/profile/reader/file/go.mod
- component/profile/reader/file/go.sum
- component/wallet-cli/go.mod
- component/wallet-cli/go.sum
- component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go
- go.mod
- go.sum
- pkg/service/oidc4vp/oidc4vp_service.go
- pkg/storage/mongodb/oidc4vptxstore/oidc4vp_tx_store.go
- test/bdd/go.mod
- test/bdd/go.sum
- test/bdd/pkg/v1/oidc4vp/vpflow_executor.go
Update VCS to use latest AFGO version.
Includes:
- Fixed bug with Marshaling/Unmarshaling SDJWT VC so all redundant workarounds are removed.  
> chore: update AFGO version

- component/event/bus.go
- component/event/bus_test.go
- component/event/mocks/publisher.gen.go
- component/event/mocks/subscriber.gen.go
- component/event/publisher.go
- component/event/publisher_test.go
- component/event/subscriber.go
- component/event/subscriber_test.go
- component/oidc/vp/requestobjectstore.go
- component/oidc/vp/requestobjectstore_test.go
- pkg/event/spi/spi.go
- pkg/event/spi/spi_test.go
- pkg/restapi/v1/issuer/controller.go
- pkg/service/oidc4ci/oidc4ci_service.go
- pkg/service/oidc4ci/oidc4ci_service_exchange_code.go
- pkg/service/oidc4ci/oidc4ci_service_exchange_code_test.go
- pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go
- pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go
- pkg/service/oidc4ci/oidc4ci_service_store_auth_code.go
- pkg/service/oidc4ci/oidc4ci_service_store_auth_code_test.go
- pkg/service/oidc4ci/oidc4ci_service_test.go
- pkg/service/oidc4vp/oidc4vp_service.go
- pkg/service/oidc4vp/oidc4vp_service_test.go
Added context.Context to Publish function signature in preparation for integration with OpenTelemetry.
Also removed options from event publisher/subscriber since they weren't being used.
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
> refactor: Added context to event Publish signature

- cmd/vc-rest/startcmd/start.go
- pkg/service/oidc4ci/models.go
- pkg/service/oidc4ci/oidc4ci_service.go
- pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go
- pkg/service/oidc4ci/oidc4ci_service_test.go
- pkg/storage/mongodb/oidc4cistore/oidc4vc_store.go
Set pre-auth code expiry time when pre-auth code gets created (same as claim data expiry) 
Add check for pre-auth code expiry to ValidatePreAuthorizedCodeRequest function.
Message returned:
"url":"/issuer/interactions/validate-pre-authorized-code",
"httpStatus":400,
"additionalMessage":"map[code:oidc-tx-not-found incorrectValue: message:invalid pre-authorization code]"
"url":"/oidc/token",
"httpStatus":400,
"additionalMessage":"map[_raw:validate pre-authorized code request: status code 400, code: oidc-tx-not-found; message: invalid pre-authorization code error:invalid_grant]"
Closes #1127
> chore: Add pre-auth code expiry

- cmd/vc-rest/startcmd/start.go
- component/credentialstatus/credentialstatus_service.go
- component/profile/reader/file/reader.go
- pkg/observability/metrics/noop/provider.go
- pkg/observability/metrics/noop/provider_test.go
- pkg/observability/metrics/prometheus/provider.go
- pkg/observability/metrics/prometheus/provider_test.go
- pkg/observability/metrics/provider.go
Added (Prometheus) HTTP client metrics. Also changed the namespace/subsystem of the HTTP server metrics to vcs/httpserver to differentiate between metrics of other microservices and also to differentiate between client and server metrics in the vcs microservice.
> feat: Added HTTP client metrics

- Makefile
- README.md
- cmd/vc-rest/main.go
- test/bdd/fixtures/docker-compose.yml
Note: project has been switched to oapi-codegen for generating Go boilerplate code based on OpenAPI 3.0 API definitions (docs/v1/openapi.yaml)
> chore: cleanup obsolete openapi spec 2.0 and demo

- pkg/restapi/v1/verifier/controller.go
- pkg/restapi/v1/verifier/controller_test.go
When multiple presentation definitions are configured in the profile and presentationDefinitionID is empty we should throw an error.
Current Behaviour: first presentation definition is picked as default to carry our OIDC presentation flow
Closes #1287
> chore: PresentationDefinitionID is REQUIRED if there are multiple PDs in profile

- pkg/restapi/v1/oidc4ci/controller.go
- pkg/restapi/v1/oidc4ci/controller_e2e_flows_test.go
- pkg/restapi/v1/oidc4ci/controller_test.go
- pkg/restapi/v1/oidc4ci/models.go
The "iat" claim check on the /credential endpoint now simply ensures that a value is set instead of requiring it to be within a specific range (which can cause issues depending on a client's clock setting).
> fix: "iat" claim check

- pkg/profile/api.go
- pkg/restapi/v1/issuer/controller.go
- pkg/restapi/v1/issuer/controller_test.go
- pkg/restapi/v1/issuer/testdata/sample_vc_invalid_university_degree.jsonld
- pkg/restapi/v1/issuer/testdata/universitydegree.schema.json
- test/bdd/features/oidc4vc_api.feature
- test/bdd/fixtures/profile/profiles.json
- test/bdd/pkg/v1/oidc4vc/oidc4ci.go
- test/bdd/pkg/v1/oidc4vc/steps.go
Added a JSON schema field to the credentialTemplate profile element. If the "jsonSchema" field is not empty then the issuer claims are validated against the schema.
> feat: Validate issuer claims against JSON schema

- pkg/restapi/v1/issuer/controller.go
- pkg/restapi/v1/issuer/controller_test.go
The profile flag, "EnforceStrictValidation" should only be used to determine whether JSON-LD validation should be performed. JSON schema validation should be performed if a JSON schema is provided.
> fix: Don't use the strict flag for JSON schema validation

- pkg/oauth2client/api.go
- pkg/profile/api.go
- pkg/restapi/v1/oidc4ci/controller.go
- pkg/restapi/v1/oidc4ci/controller_test.go
- pkg/service/clientmanager/client_manager.go
- pkg/service/clientmanager/client_manager_test.go
This PR fixes the following issues:
* OAuth client manager uses values for `grant_types_supported`, `response_types_supported` and `token_endpoint_auth_methods_supported` from issuer's profile (OIDCConfig property). It's wrong as these values are supposed to be used when making calls to issuer's OIDC provider. VCS acts as an OIDC provider as well (e.g. for wallet) but it should use its own values here depending on what is actually implemented and supported (e.g. for `grant_type` only `authorization_code` and `urn:ietf:params:oauth:grant-type:pre-authorized_code` are supported).
* Support for client secret expiration is not implemented properly (i.e. it doesn't make sense to issue client ID with secret that will expire in 5 min) - so, for now, proposal is to create clients with secrets …
> fix: params for oauth client manager

- component/profile/reader/file/reader.go
- pkg/profile/api.go
- pkg/service/verifypresentation/verifypresentation_service.go
- pkg/service/verifypresentation/verifypresentation_service_test.go
- test/bdd/bddtests_test.go
- test/bdd/features/oidc4vc_api.feature
- test/bdd/fixtures/profile/profiles.json
if issuer signing did exists in trust list  and credentialsTypes are empty  = **we trust to all credentials types from this issuer**.
if issuer signing did exists in trust list  and credentialsTypes are not empty  = **we trust to only specified credentialTypes from this issuer**.
> feat: trustlist v2 (with type filter)

- pkg/observability/tracing/wrappers/verifypresentation/verifypresentation_wrapper.go
- pkg/observability/tracing/wrappers/verifypresentation/verifypresentation_wrapper_test.go
- pkg/restapi/v1/verifier/controller.go
- pkg/restapi/v1/verifier/controller_test.go
- pkg/service/oidc4vp/oidc4vp_service.go
- pkg/service/oidc4vp/oidc4vp_service_test.go
- pkg/service/verifypresentation/api.go
- pkg/service/verifypresentation/verifypresentation_service.go
- pkg/service/verifypresentation/verifypresentation_service_test.go
- scripts/check_lint.sh
- test/bdd/go.mod
fatal error: concurrent map writes
goroutine 26200 [running]:
github.com/trustbloc/vcs/pkg/service/verifypresentation.(*Service).checkCredentialStrict(0xc00015b9c0, {0x2028368, 0xc005c7a810}, {0xc000302ba0, 0x1, 0xc003d39c40?})
/go/src/github.com/trustbloc/vcs/.build/vcs/pkg/service/verifypresentation/verifypresentation_service.go:205 +0x1f7
github.com/trustbloc/vcs/pkg/service/verifypresentation.(*Service).VerifyPresentation(0xc00015b9c0, {0x2028368, 0xc005c7a810}, 0xc007628f20, 0x0?, 0xc0072562c0)
> fix: claims keys concurrency

- component/credentialstatus/credentialstatus_service.go
- pkg/event/spi/spi.go
RoutingKey is an optional key that is used by the event bus to determining how/where to route the event.
Set the routing key to be the CSL URL for credential status update events.
> feat: Add routing key to event

- pkg/service/trustregistry/api.go
- pkg/service/trustregistry/trustregistry_service.go
- pkg/service/trustregistry/trustregistry_service_test.go
- test/bdd/trustregistry/models.go
- test/bdd/trustregistry/server.go
The trust-registry issuer endpoint request now includes an array of attestations and an array or credential types.
> feat: Update trust-registry issuer endpoint

- pkg/service/oidc4vp/api.go
- pkg/service/oidc4vp/oidc4vp_service.go
- pkg/service/oidc4vp/oidc4vp_service_test.go
Added an array of credential fields to the verifier.oidc-interaction-succeeded and verifier.oidc-interaction-claims-retrieved event payloads:
- Credential ID
- Credential types
- Credential subject ID
- Issuer ID
> feat: Additional fields in verifier oidc events payload

- component/wallet-cli/pkg/trustregistry/models.go
- component/wallet-cli/pkg/trustregistry/trustregistry.go
- pkg/service/oidc4vp/oidc4vp_service.go
- pkg/service/trustregistry/api.go
- pkg/service/trustregistry/trustregistry_service.go
- pkg/service/trustregistry/trustregistry_service_test.go
- test/bdd/trustregistry/models.go
- test/bdd/trustregistry/server.go
The trust-registry wallet presentation and verifier requests were updated such that the field, credential_metadata, was renamed to credential_matches.
> refactor: Rename trust-registry request field to credential_matches

- pkg/doc/verifiable/format.go
- pkg/profile/api.go
- pkg/restapi/v1/issuer/controller.go
- pkg/restapi/v1/issuer/controller_test.go
- test/bdd/features/oidc4vc_api.feature
- test/bdd/fixtures/profile/profiles.json
- test/bdd/pkg/v1/oidc4vc/oidc4vci.go
- test/bdd/pkg/v1/oidc4vc/steps.go
The 'model' parameter on the issuer profile specifies the credential model for the issuer. Supported models are w3c-vc-1.1 and w3c-vc-2.0.
> feat: Added VC model parameter to issuer profile config

- component/credentialstatus/credentialstatus_service_test.go
- pkg/cslmanager/cslmanager.go
- pkg/cslmanager/cslmanager_test.go
- pkg/doc/vc/status.go
- pkg/doc/vc/statustype/common.go
- pkg/doc/vc/statustype/revocationlist2020.go
- pkg/doc/vc/statustype/revocationlist2020_test.go
- pkg/doc/vc/statustype/revocationlist2021.go
- pkg/doc/vc/statustype/revocationlist2021_test.go
- pkg/doc/vc/statustype/statuslist2021.go
- pkg/doc/vc/statustype/statuslist2021_test.go
- pkg/doc/vc/statustype/statuslist_bitstring.go
- pkg/doc/vc/statustype/statuslist_bitstring_test.go
- pkg/doc/vc/statustype/statusprocessor.go
- pkg/doc/vc/statustype/statusprocessor_test.go
- pkg/doc/vc/vcutil/vcutil.go
- pkg/doc/vc/vcutil/vcutil_test.go
- pkg/internal/mock/status/status.go
- pkg/kms/aws/service_mocks.go
- pkg/kms/mocks/kms_mocks.go
- pkg/service/issuecredential/issuecredential_service.go
- test/bdd/fixtures/profile/profiles.json
Added support for BitstringStatusListEntry status list type which is compatible with VC model 2.0.
> feat: BitstringStatusList for VC model 2.0

- cmd/vc-rest/startcmd/params.go
- pkg/observability/tracing/tracing.go
- pkg/observability/tracing/tracing_test.go
- test/bdd/fixtures/docker-compose.yml
Deprecated the JAEGER exporter type and added DEFAULT to the list of supported types. Also fixed the BDD test to work with the latest version of otel.
> chore: Deprecate JAEGER tracing exporter

- cmd/vc-rest/startcmd/start.go
request object expiration is managed by s3 lifecycle rules
> chore: remove outdated TODO comment (vp ttl)

- pkg/service/verifycredential/verifycredential_service.go
- pkg/service/verifypresentation/verifypresentation_service.go
- scripts/check_lint.sh
**VC**
According to the spec https://www.w3.org/TR/vc-data-integrity/#proofs, VC can have multiple proofs (Proof Sets), which is currently supported.
Proof Graphs & Chains are more advanced features that are not currently supported by vcs & vc-go.
**VP**
The spec does not directly mention that the VP should have only 1 Proof because the VP is VC. We will handle it like VC during proof validation.
As we generate options (challenge, domain, etc.) during the OIDC4VP flow, we expect that all proofs will have this option in the presentation.
> feat: add logic to validate multi proof vc\vp

- pkg/doc/vc/crypto/crypto.go
in VSC infrastructure did-go is responsible for resolving dids.
did:sov is not supported by did-go library, so we don't need this code.
> feat: drop did:sov
