.golangci.yml, doc.go, go.mod
=> chore: project setup minor fix

cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
Create verify credential endpoint that will validate credential.
Closes #18
=> feat: Verify Credential Endpoint

test/bdd/fixtures/vc-rest/.env, test/bdd/fixtures/vc-rest/docker-compose.yml
=> chore: Add docker compose for vc-rest

pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, pkg/restapi/vc/operation/profile.go, pkg/restapi/vc/operation/profile_test.go
User verifiable package to add signature to VC
Verify signed VC
Closes #24
=> feat: Sign and Verify VC (JSONLD Signature)

pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, pkg/restapi/vc/operation/profile_test.go
=> fix: Issuer info should be read from profile instead of create request

cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, scripts/check_unit.sh
=> feat: Fix the cmd vc-rest unit-test

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/internal/mock/client.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: update edv version and remove the url stripping

cmd/vc-rest/go.sum, go.mod, go.sum
=> chore: Update github.com/hyperledger/aries-framework-go revision

cmd/vc-rest/go.sum, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> chore: Comment out signCredential

pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: storeVC handler model refactor

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> chore: Uncomment sign credential

pkg/restapi/vc/operation/operations.go
=> feat: Quick fix to store vc credential

pkg/restapi/vc/operation/operations.go
=> chore: Remove hard-coded profile

README.md, docs/vc-rest/README.md
=> docs: Describe edge-service components

ci/version_var.sh, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, docs/vc-rest/README.md, go.mod, go.sum, test/bdd/fixtures/edv-rest/.env, test/bdd/go.sum
=> chore: Release 0.1.1

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, go.mod, go.sum, pkg/internal/mock/edv/client.go, pkg/restapi/vc/controller.go, pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, pkg/utils/cmd/util.go, pkg/utils/cmd/util_test.go, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/go.sum
=> feat: Add sidetree to vc-rest

.gitignore, Makefile, scripts/generate_test_keys.sh, test/bdd/bddtests_test.go, test/bdd/dockerutil/compose.go, test/bdd/fixtures/sidetree-mock/.env, test/bdd/fixtures/sidetree-mock/docker-compose.yml
=> chore: Add sidetree-mock docker container

test/bdd/pkg/vc/vc_steps.go
=> fix: Add response info to error message

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/context/context.go, test/bdd/pkg/vc/vc_steps.go
=> feat: Using DID key to sign and verify VC

pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/pkg/context/context.go
Signed-off-by: amod kala <amod.kala@securekey.com>
=> feat: enabled custom context for create credential request

pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, pkg/doc/vc/profile/profile.go, pkg/doc/vc/profile/profile_test.go, pkg/doc/vc/status/csl/csl.go, pkg/doc/vc/status/csl/csl_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/bddtests_test.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/vc/vc_steps.go
=> feat: Add Credential Status List

cmd/vc-rest/startcmd/start.go, pkg/restapi/vc/controller.go, pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/features/vc_e2e_api.feature, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/pkg/vc/vc_steps.go
=> feat: Check vc status

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update to latest aries framework

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/edv-rest/.env, test/bdd/fixtures/edv-rest/docker-compose.yml, test/bdd/go.sum
=> feat: Update CouchDB to latest version

ci/version_var.sh
=> chore: Complete release 0.1.2

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, pkg/doc/vc/profile/profile.go, pkg/doc/vc/profile/profile_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/features/vc_e2e_api.feature, test/bdd/fixtures/universalresolver/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/context/context.go, test/bdd/pkg/vc/vc_steps.go
=> chore: Integrate with veres did

cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, pkg/restapi/vc/controller.go, pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> chore: #93 Split available REST operations by mode

pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/features/vc_e2e_api.feature, test/bdd/pkg/context/context.go, test/bdd/pkg/vc/vc_steps.go
=> feat: Add Verify presentation endpoint

test/bdd/fixtures/universalresolver/docker-compose.yml, test/bdd/fixtures/universalresolver/run-uni-resolver-web.sh
=> fix: uni-resolver image

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, go.mod, go.sum, pkg/doc/vc/status/csl/csl.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/bddtests_test.go, test/bdd/fixtures/couchdb/docker-compose.yml, test/bdd/fixtures/did-method-rest/docker-compose.yml, test/bdd/fixtures/discovery-server/docker-compose.yml, test/bdd/fixtures/dns-proxy-server/docker-compose.yml, test/bdd/fixtures/edv-rest/docker-compose.yml, test/bdd/fixtures/sidetree-mock/docker-compose.yml, test/bdd/fixtures/stakeholder-server/docker-compose.yml, test/bdd/fixtures/universalresolver/docker-compose.yml, test/bdd/fixtures/vc-rest/.env, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/go.sum, test/bdd/pkg/vc/vc_steps.go
=> feat: Add couchdb option to vc-rest

pkg/doc/vc/status/csl/csl.go, pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/pkg/vc/vc_steps.go
=> feat: Add check status endpoint in vc-rest

pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
https://w3c-ccg.github.io/vc-issuer-http-api/#/internal/issueCredential
closes #116 
=> feat: Issue Credential API

pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
- New API to generate keypair from KMS
- Moved getPublicKey from DID Document logic to a common function
closes #123 
=> feat: KMS Generate Keypair API

pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/bddtests_test.go, test/bdd/features/verifier_e2e_api.feature, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/verifier/verifier_steps.go
- Implement https://w3c-ccg.github.io/vc-verifier-http-api/#/internal/verifyCredential
- BDD test
closes #129 
=> feat: Verifications API

test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go, test/bdd/pkg/verifier/verifier_steps.go
=> refactor: Move common code to BDD test utils

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> refactor: Add default Verifications API checks

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/pkg/issuer/issuer_steps.go
=> feat: composeAndIssueCredential API - Use ProofFormat and ProofFormatOptions from the request to sign VC

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/internal/mock/didbloc/client.go, pkg/restapi/vc/operation/operations.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/discovery-server/docker-compose.yml, test/bdd/fixtures/sidetree-mock/.env, test/bdd/fixtures/stakeholder-server/config-data/stakeholder.one:8088.json, test/bdd/fixtures/stakeholder-server/docker-compose.yml, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go
=> feat: Enable tls for sidetree-mock

test/bdd/fixtures/did-method-rest/.env
=> chore: update did method image tag

pkg/restapi/vc/operation/operations.go
=> feat: add tls config to http client in vc-rest

pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/features/verifier_e2e_api.feature, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/vc/vc_steps.go, test/bdd/pkg/verifier/verifier_steps.go
- Implement https://w3c-ccg.github.io/vc-verifier-http-api/#/internal/verifyPresentation API
- BDD tests
closes #150 
=> feat: Verify Presentation API

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: verifyCredential API - Status Check

test/bdd/features/vc_e2e_api.feature, test/bdd/pkg/vc/vc_steps.go
=> test: BDD test refactor to use W3C Verifier APIs

pkg/restapi/vc/operation/models.go
=> refactor: Verifier API - Update json tag name

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, test/bdd/fixtures/edv-rest/.env
=> chore: Add TLS config to edv client

cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go
=> feat: Add tls config for universalResolverVDRI

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go
=> chore: Update sidetree-mock and trustbloc-did-method images

test/bdd/features/verifier_e2e_api.feature, test/bdd/pkg/issuer/issuer_steps.go
=> fix: incorrect sentence in feature file

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/pkg/vc/vc_steps.go, test/bdd/pkg/verifier/verifier_steps.go, test/bdd/testdata/university_degree_credential.json
- Credential Status addition in APIs
- Update BDD tests
closes #173 
=> refactor: BDD tests - switch to W3C Issuer API

cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, scripts/prepare-test-verifiables.js, test/bdd/features/vc_e2e_api.feature, test/bdd/features/verifier_e2e_api.feature, test/bdd/fixtures/universalresolver/config.json, test/bdd/pkg/context/context.go, test/bdd/testdata/danubetech_vc1.json, test/bdd/testdata/danubetech_vc2.json, test/bdd/testdata/digitalbazaar_vc1.json, test/bdd/testdata/transmute_vp1.json, test/bdd/testdata/transmute_vp2.json
=> feat: interop tests with danubetech & digital bazaar VCs

scripts/prepare-test-verifiables.js, test/bdd/testdata/danubetech_vc1.json, test/bdd/testdata/danubetech_vc2.json, test/bdd/testdata/digitalbazaar_vc1.json, test/bdd/testdata/transmute_vp1.json, test/bdd/testdata/transmute_vp2.json
=> chore: danubetech VC samples to use did:sov

pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> refactor: Send Response Error Message inside a JSON

pkg/restapi/vc/operation/openapi.go, pkg/restapi/vc/operation/operations.go
=> refactor: Update OpenAPI uri and models

pkg/restapi/vc/operation/openapi.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> docs: OpenAPI documentation

Makefile
=> fix: Add generate test config target to OpenAPI demo

pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/operations.go
=> refactor: Remove verification API from Issuer mode

ci/azure-pipelines.yml, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go
=> chore: Add bdd test to check DID service

cmd/vc-rest/startcmd/start.go
=> fix: tls-systemcertpool flag

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/discovery-server/config-data/consortium.json, test/bdd/fixtures/stakeholder-server/config-data/stakeholder.one:8088.json, test/bdd/go.mod, test/bdd/go.sum
=> chore: Remove hard-coded memory storage

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/vc/vc_steps.go, test/bdd/pkg/verifier/verifier_steps.go
=> feat: domain and challenges in proof

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/operations.go, test/bdd/features/thirdparty_verifier_e2e.feature, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/bddutil/util.go
=> fix: interop - verifiable presentation verification issue

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go
=> refactor: Update Issuer API success response to 201

pkg/doc/vc/profile/profile.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> chore: Make credential status optional

pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go
=> fix: add DisableVCStatus to profile

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> fix: empty credential schema

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, go.mod, go.sum, test/bdd/fixtures/did-method-rest/docker-compose.yml, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum
=> feat: Add couchdb prefix

test/bdd/fixtures/discovery-server/docker-compose.yml
=> fix: switch to static-file-server v1.7.2

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: Issue Credential API - Add issuer.ID and proofPurpose validation

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, test/bdd/go.mod, test/bdd/go.sum
=> refactor: Search private key from profile if verificationMethod matches the profile DID

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/pkg/vc/vc_steps.go
=> refactor: Validate status only if VC contains status data

pkg/restapi/vc/operation/operations.go
=> fix: issueCredential API - Ignore proof in the input request

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/vc/vc_steps.go
=> chore: Update sidetree-core revision

cmd/vc-rest/go.sum, go.sum, pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/go.sum, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go, test/bdd/pkg/verifier/verifier_steps.go
=> feat: Support for proof challenge and domain

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/operations.go, test/bdd/go.mod, test/bdd/go.sum
=> refactor: IssueCred API - Add VC validation without proof check

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update did method version

cmd/vc-rest/go.mod, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, internal/cryptosetup/cryptosetup.go, pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/pkg/verifier/verifier_steps.go
=> feat: Key persistent storage

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/operations.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go
=> chore: update sidetree-mock image

pkg/doc/vc/profile/profile.go, pkg/doc/vc/profile/profile_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/openapi.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: Holder Mode - Create and Get Profile API

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
Validation logic update based on https://github.com/w3c-ccg/vc-examples/issues/62
part of #327 
=> feat: Update to Proof challenge/domain validation

test/bdd/features/thirdparty_verifier_e2e.feature, test/bdd/pkg/vc/vc_steps.go
=> fix: bdd-interop-test

cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start_test.go, go.sum, internal/cryptosetup/cryptosetup_test.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/go.sum
=> test: Increase unit test coverage for persistent KMS code

pkg/restapi/vc/operation/operations.go, test/bdd/pkg/vc/vc_steps.go
=> refactor: Remove example service from DID documents

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/operations.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: create p256 in iee1363 format

pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/openapi.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: Holder Sign Presentation API

test/bdd/pkg/vc/vc_steps.go
=> test: Verify presentation generated from Holder API along with challenge/domain

README.md, docs/vc-rest/api_overview.md, docs/vc-rest/vc_interop_api_impl_status.md, pkg/restapi/vc/operation/operations.go
=> docs: W3C API status doc and Holder API Overview

pkg/doc/vc/status/csl/csl.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: Add CredentialStatus2017 context

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: Add JsonWebSignature2020 context

cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go
=> feat: Healthcheck API

pkg/restapi/vc/operation/operations.go
=> fix: JSON-LD strict mode VC validation

internal/cryptosetup/cryptosetup.go, internal/cryptosetup/cryptosetup_test.go, pkg/restapi/vc/operation/operations.go
=> refactor: Crypto setup code

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/operations.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: update sidetree-mock image tag

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/operations.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: update trustbloc-did-method revision

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/vc/operation/operations.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: Support for TrustBloc DID Authentication and Assertion data

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/edv-rest/.env, test/bdd/fixtures/vc-rest/.env, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/go.sum
=> chore: Update EDV version

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, pkg/doc/vc/status/csl/csl_test.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go
=> feat: Validate Signing/Verification proof purpose in DID Document 

ci/azure-pipelines.yml, scripts/check_integration.sh, test/bdd/fixtures/universalresolver/config.json, test/bdd/fixtures/universalresolver/docker-compose.yml, test/bdd/pkg/bddutil/util.go
=> chore: update v1 uniresolver image

pkg/doc/vc/crypto/crypto.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/pkg/holder/holder_steps.go, test/bdd/pkg/issuer/issuer_steps.go
=> fix: Sign presentation - set default proofPurpose to authentication

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/stakeholder-server/config-data/testnet.trustbloc.local.json, test/bdd/go.mod, test/bdd/go.sum
=> chore: update trustbloc-did-method dependency and bdd test to match

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: update trustbloc-did-method dependency

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: update trustbloc did method

cmd/did-rest/go.sum, images/did-rest/Dockerfile, images/vc-rest/Dockerfile
=> chore: add nsswitch to image

cmd/did-rest/startcmd/start.go, cmd/did-rest/startcmd/test/config.json, pkg/proxy/rules/filerules/provider_test.go, pkg/proxy/rules/filerules/test/config.json, pkg/restapi/did/controller_test.go, pkg/restapi/did/operation/operations.go, pkg/restapi/did/operation/operations_test.go, test/bdd/fixtures/did-rest/config.json
- remove unused external host var
- allign pattern to match uni resolver convention
Closes #388
=> chore: Remove unused external host var

pkg/doc/vc/profile/profile.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/features/w3c_chapi_http.feature, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/context/context.go, test/bdd/pkg/vc/vc_steps.go
- https://github.com/w3c-ccg/vc-examples/blob/master/docs/chapi-http-edu/README.md
=> test: W3C CHAPI API flow

ci/azure-pipelines.yml, scripts/check_integration.sh, test/bdd/features/w3c_chapi_http.feature, test/bdd/pkg/vc/vc_steps.go
=> test: CHAPI flow - add support for JsonWebSignature2020 and P256/Ed25519 key in profile

test/bdd/fixtures/did-rest/config.json
=> chore: add driver-did-factom

cmd/vc-rest/startcmd/start.go, test/bdd/fixtures/did-rest/docker-compose.yml
=> feat: Support for DID Factom

pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> feat: Perform checks on VCs embedded inside VPs

pkg/restapi/vc/operation/operations.go
=> fix: Skip domain/challenge validation for VCs inside VP

cmd/vc-rest/startcmd/start.go, pkg/doc/vc/crypto/crypto.go, pkg/restapi/vc/operation/operations.go
=> chore: Add issues to the TODO and remove implemented TODOs

pkg/restapi/did/operation/operations.go, test/bdd/fixtures/universalresolver/config.json
=> chore: Add timeout per request

test/bdd/fixtures/sidetree-mock/.env
=> ci: update sidetree-mock packages

pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go
=> refactor: Remove deprecated /verifications API

cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, pkg/doc/vc/profile/profile.go, pkg/doc/vc/profile/profile_test.go, pkg/restapi/holder/controller.go, pkg/restapi/holder/operation/models.go, pkg/restapi/holder/operation/openapi.go, pkg/restapi/holder/operation/operations.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/internal/common/http/common.go, pkg/restapi/model/model.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/openapi.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, test/bdd/pkg/holder/holder_steps.go, test/bdd/pkg/vc/vc_steps.go
=> refactor: move holder logic from operations.go

Makefile, scripts/check_integration_interop.sh
=> chore: interop merge build script

cmd/vc-rest/startcmd/start.go, pkg/restapi/vc/controller_test.go, pkg/restapi/vc/operation/models.go, pkg/restapi/vc/operation/openapi.go, pkg/restapi/vc/operation/operations.go, pkg/restapi/vc/operation/operations_test.go, pkg/restapi/verifier/controller.go, pkg/restapi/verifier/operation/models.go, pkg/restapi/verifier/operation/openapi.go, pkg/restapi/verifier/operation/operations.go, test/bdd/pkg/vc/vc_steps.go, test/bdd/pkg/verifier/verifier_steps.go
=> refactor: move verifier logic from operation.go

pkg/restapi/holder/operation/operations_test.go, pkg/restapi/verifier/operation/operations_test.go
=> test: Add Verifier/Holder tests (removed during code refactor)

Makefile, ci/azure-pipelines.yml, test/bdd/features/verifier_e2e_api.feature
=> chore: interop test behaviour test

cmd/vc-rest/startcmd/start.go, pkg/internal/mock/kms/kms.go, pkg/restapi/holder/controller.go, pkg/restapi/holder/controller_test.go, pkg/restapi/holder/operation/operations.go, pkg/restapi/holder/operation/operations_test.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/internal/common/did/common_test.go, pkg/restapi/issuer/controller.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/verifier/controller.go, pkg/restapi/verifier/controller_test.go, pkg/restapi/verifier/operation/operations.go, pkg/restapi/verifier/operation/operations_test.go
=> chore: Add missing unit test for new packages

cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, go.mod, go.sum, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/go.mod, test/bdd/go.sum
=> fix: Add retrieve VC retries

cmd/vc-rest/startcmd/start.go, pkg/doc/vc/profile/verifier/profile.go, pkg/doc/vc/profile/verifier/profile_test.go, pkg/restapi/verifier/controller.go, pkg/restapi/verifier/controller_test.go, pkg/restapi/verifier/operation/openapi.go, pkg/restapi/verifier/operation/operations.go, pkg/restapi/verifier/operation/operations_test.go
=> feat: Support for verifier profile

cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, pkg/restapi/verifier/operation/operations.go, pkg/restapi/verifier/operation/operations_test.go, test/bdd/fixtures/vc-rest/docker-compose.yml, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/holder/holder_steps.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go
=> feat: bearer authorization token support

cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum
Signed-off-by: Dmitriy Kinoshenko <dkinoshenko@gmail.com>
=> chore: aries version update

cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/discovery-server/config-data/testnet.trustbloc.local.json, test/bdd/fixtures/stakeholder-server/config-data/stakeholder.one:8088.json, test/bdd/fixtures/stakeholder-server/config-data/testnet.trustbloc.local.json, test/bdd/go.mod, test/bdd/go.sum
=> chore: update trustbloc-did-method dependency and config cache lifetime

test/bdd/fixtures/edv-rest/.env
=> chore: Update EDV image

cmd/did-rest/startcmd/start.go, cmd/did-rest/startcmd/start_test.go, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go
=> feat: Set log level via command line flag

cmd/did-rest/startcmd/start.go, cmd/vc-rest/startcmd/start.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/logspec/controller.go, pkg/restapi/logspec/controller_test.go, pkg/restapi/logspec/operation/openapi.go, pkg/restapi/logspec/operation/operations.go, pkg/restapi/logspec/operation/operations_test.go, pkg/restapi/verifier/operation/operations_test.go
=> feat: Endpoints for changing/retrieving logging level on the fly

cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/internal/common/did/common.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go
Update did-method/sidetree
Closes #460
=> chore: update did-method/sidetree

cmd/common/common.go, cmd/common/common_test.go, cmd/did-rest/startcmd/start.go, cmd/did-rest/startcmd/start_test.go, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go
=> refactor: Reduce code duplication in the cmd files

pkg/restapi/governance/operation/operations.go
=> fix: governance credential is incorrect

test/bdd/fixtures/sidetree-mock/.env
=> chore: update sidetree-mock 0.1.4

cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/did-method-rest/.env
=> chore: update to latest aries-framework-go and trustbloc-did-method

README.md, docs/build.md
=> docs: Move build instruction to build.md from README.md

ci/version_var.sh
=> chore: Complete Release 0.1.4

Makefile, ci/azure-pipelines.yml, cmd/did-rest/go.mod, cmd/vc-rest/go.mod, docs/build.md, go.mod, test/bdd/go.mod
=> chore: Update to Go 1.15

pkg/doc/vc/profile/profile.go, pkg/internal/mock/edv/client.go, pkg/restapi/internal/common/vcutil/vcutil.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/fixtures/edv-rest/.env, test/bdd/pkg/vc/vc_steps.go
=> feat: store edv vaultID in issuer profiles

.gitignore, scripts/check_unit.sh, test/bdd/fixtures/universal-registrar/docker-compose.yml
=> fix: uni-registrar-web image

pkg/doc/vc/profile/verifier/profile.go, pkg/doc/vc/profile/verifier/profile_test.go, pkg/restapi/verifier/controller_test.go, pkg/restapi/verifier/operation/openapi.go, pkg/restapi/verifier/operation/operations.go, pkg/restapi/verifier/operation/operations_test.go, test/bdd/features/verifier_e2e_api.feature, test/bdd/pkg/verifier/verifier_steps.go
=> feat: delete verifier profile api

cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/verifier/operation/operations.go, test/bdd/go.mod, test/bdd/go.sum
=> fix: remove 'deleted' string check in verifier

pkg/doc/vc/profile/profile.go, pkg/doc/vc/profile/profile_test.go, pkg/restapi/holder/controller_test.go, pkg/restapi/holder/operation/openapi.go, pkg/restapi/holder/operation/operations.go, pkg/restapi/holder/operation/operations_test.go, test/bdd/features/holder_e2e_api.feature, test/bdd/pkg/holder/holder_steps.go
=> feat: delete holder profile api

pkg/doc/vc/profile/profile.go, pkg/doc/vc/profile/profile_test.go, pkg/restapi/issuer/controller_test.go, pkg/restapi/issuer/operation/openapi.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/features/issuer_e2e_api.feature, test/bdd/pkg/issuer/issuer_steps.go
=> feat: issuer delete profile api

.golangci.yml, cmd/did-rest/main_test.go, cmd/did-rest/startcmd/start.go, cmd/vc-rest/main_test.go, cmd/vc-rest/startcmd/start.go, pkg/client/uniregistrar/client.go, pkg/client/uniregistrar/client_test.go, pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/profile/profile.go, pkg/doc/vc/status/csl/csl.go, pkg/internal/cryptosetup/cryptosetup.go, pkg/proxy/rules/filerules/provider.go, pkg/restapi/governance/operation/operations.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/internal/common/vcutil/vcutil_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/model/model.go, pkg/restapi/verifier/operation/operations.go, scripts/check_lint.sh, test/bdd/bddtests_test.go, test/bdd/dockerutil/compose.go, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/context/context.go, test/bdd/pkg/governance/governance_steps.go, test/bdd/pkg/holder/holder_steps.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go
=> chore: update golangci-lint to v1.31

test/bdd/features/vc_e2e_api.feature, test/bdd/features/verifier_e2e_api.feature
=> chore: enabled fixed interop tests

cmd/did-rest/main_test.go, cmd/vc-rest/main_test.go, cmd/vc-rest/startcmd/start.go, pkg/doc/vc/crypto/crypto.go, pkg/internal/cryptosetup/cryptosetup.go, pkg/restapi/governance/operation/operations_test.go, pkg/restapi/holder/operation/operations_test.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/issuer/operation/operations.go
=> refactor: remove minor nolint

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/restapi/internal/common/did/common.go, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go
=> chore: update trustbloc-did-method and sidetree-mock

docs/vc-rest/api_overview.md
=> docs: profile apis and holder sign presentations api

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/internal/mock/edv/client.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/fixtures/edv-rest/.env
=> chore: Update EDV dependency

cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/fixtures/sidetree-mock/.env, test/bdd/go.mod, test/bdd/go.sum
Update sidetree mock, did-method
Closes #459
=> chore: Update sidetree, did-method

cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/status/csl/csl_test.go, test/bdd/go.mod, test/bdd/go.sum
=> chore: update aries dependency

ci/version_var.sh
=> chore: Complete Release 0.1.5

Makefile, ci/azure-pipelines.yml, ci/version_var.sh, images/did-rest/Dockerfile, images/vc-rest/Dockerfile, test/bdd/fixtures/did-method-rest/.env, test/bdd/fixtures/did-rest/.env, test/bdd/fixtures/edv-rest/.env, test/bdd/fixtures/sidetree-mock/.env, test/bdd/fixtures/vc-rest/.env
=> ci: migrate to ghcr

pkg/doc/vc/crypto/crypto_test.go, pkg/doc/vc/profile/profile.go, pkg/doc/vc/profile/profile_test.go, pkg/doc/vc/status/csl/csl_test.go, pkg/restapi/governance/operation/operations.go, pkg/restapi/governance/operation/operations_test.go, pkg/restapi/holder/operation/operations.go, pkg/restapi/holder/operation/operations_test.go, pkg/restapi/internal/common/vcutil/vcutil.go, pkg/restapi/internal/common/vcutil/vcutil_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/pkg/context/context.go, test/bdd/pkg/governance/governance_steps.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go
=> feat: Add vc status to governance vcs

pkg/restapi/governance/operation/operations.go
=> fix: add Issued field

Makefile
=> fix: build comparator-rest for bdd-interop-test

Makefile, test/bdd/features/vc_e2e_api.feature, test/bdd/features/verifier_e2e_api.feature
=> chore: comment out failing interop test

README.md, cmd/vault-server/README.md, cmd/vault-server/docs/openapi.yaml
=> docs: document vault-server

README.md, cmd/comparator-rest/README.md, cmd/comparator-rest/docs/openapi.yaml
=> docs: comparator openapi specs and README

pkg/client/vault/client.go, pkg/client/vault/client_test.go, pkg/restapi/vault/operation/openapi.go, pkg/restapi/vault/operation/operations.go, pkg/restapi/vault/operation/operations_test.go
Implements get documents metadata endpoint.
=> feat: Implements get documents metadata endpoint.

cmd/vault-server/startcmd/start.go, pkg/restapi/healthcheck/controller.go, pkg/restapi/healthcheck/operation/operations.go, test/bdd/features/vault_server_e2e_api.feature
=> feat: Vault Server - Health check endpoint

test/bdd/features/vault_server_e2e_api.feature, test/bdd/fixtures/vault-server/.env, test/bdd/pkg/vault/vault_steps.go
=> test: Vault Server BDD tests

cmd/comparator-rest/go.sum, cmd/comparator-rest/startcmd/start.go, cmd/comparator-rest/startcmd/start_test.go, pkg/client/csh/client.go, pkg/client/csh/client_test.go, pkg/restapi/comparator/operation/openapi.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/comparator/operation/operations_test.go, scripts/generate_test_keys.sh, test/bdd/bddtests_test.go, test/bdd/fixtures/comparator-rest/docker-compose.yml
=> feat: comparator: Register at Confidential Hub Storage at startup

cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.sum, cmd/vault-server/go.sum, cmd/vault-server/startcmd/start.go, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/client/vault/client.go, test/bdd/features/vault_server_e2e_api.feature, test/bdd/fixtures/vault-server/docker-compose.yml, test/bdd/go.sum, test/bdd/pkg/vault/vault_steps.go
=> feat: Vault server TLS support

ci/azure-pipelines.yml
=> fix: rename confidential-storage-hub to hub-confidential-storage

pkg/restapi/comparator/operation/models.go, pkg/restapi/comparator/operation/operations.go
=> fix: config keys for comparator

pkg/client/vault/client.go, pkg/client/vault/client_test.go, pkg/restapi/vault/operation/operations.go, pkg/restapi/vault/operation/operations_test.go, test/bdd/features/vault_server_e2e_api.feature, test/bdd/fixtures/vault-server/docker-compose.yml, test/bdd/pkg/vault/vault_steps.go
=> fix: Vault server - generates id when it is empty.

cmd/comparator-rest/go.sum, cmd/comparator-rest/startcmd/start.go, cmd/comparator-rest/startcmd/start_test.go, cmd/vault-server/startcmd/start.go, pkg/client/vault/client.go, pkg/client/vault/client_test.go, pkg/restapi/comparator/operation/models.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/comparator/operation/operations_test.go, pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go, pkg/restapi/vault/operation/openapi.go, pkg/restapi/vault/operation/operations.go, pkg/restapi/vault/operation/operations_test.go, test/bdd/fixtures/comparator-rest/docker-compose.yml, test/bdd/pkg/vault/vault_steps.go
=> chore: configure vault url in comparator server 

pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go, test/bdd/pkg/vault/vault_steps.go
=> fix: Vault server - id is a did (not did URL)

pkg/client/vault/reader.go, pkg/client/vault/reader_test.go, pkg/restapi/csh/operation/zcapld/dependencies.go, pkg/restapi/csh/operation/zcapld/zcapld.go, pkg/restapi/csh/operation/zcapld/zcapld_test.go
=> feat: /compare utilities

pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go
=> fix: Vault server - removes restriction for the EDV ID

pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go, pkg/restapi/vault/operation/operations.go, pkg/restapi/vault/operation/operations_test.go, test/bdd/features/vault_server_e2e_api.feature, test/bdd/pkg/vault/vault_steps.go
=> feat: Vault server - get authorization.

pkg/client/vault/client.go, pkg/client/vault/client_test.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go, pkg/restapi/vault/operation/openapi.go, pkg/restapi/vault/operation/operations.go, pkg/restapi/vault/operation/operations_test.go, test/bdd/pkg/vault/vault_steps.go
=> feat: Vault server - adds client

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/client/vault/client.go, pkg/client/vault/client_test.go, pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go, pkg/restapi/vault/operation/openapi.go, pkg/restapi/vault/operation/operations.go, test/bdd/features/vault_server_e2e_api.feature, test/bdd/fixtures/edv-rest/.env, test/bdd/fixtures/vault-server/.env, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/vault/vault_steps.go
=> feat: Vault server - adds caveat expiry support

pkg/restapi/vault/client.go
=> fix: Vault server - builds proper URL

pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go
=> feat: Vault server - adds encKeyURI to the response

pkg/restapi/vault/client.go, test/bdd/pkg/vault/vault_steps.go
=> fix: Vault server - fixes EDV URL

cmd/comparator-rest/go.sum, cmd/comparator-rest/startcmd/start_test.go, pkg/client/csh/models/caveat.go, pkg/client/csh/models/operator.go, pkg/client/csh/models/query.go, pkg/restapi/comparator/controller_test.go, pkg/restapi/comparator/operation/compare.go, pkg/restapi/comparator/operation/openapi/config.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/comparator/operation/operations_test.go, test/bdd/features/comparator_e2e_api.feature, test/bdd/go.mod, test/bdd/pkg/comparator/comparator_steps.go, test/bdd/pkg/vault/vault_steps.go
=> chore: integrate with csh compare endpoint

cmd/comparator-rest/docs/openapi.yaml, cmd/vault-server/docs/openapi.yaml
Downgraded to Swagger 2.0 format due to technical limitations with golang tooling.
=> refactor: comparator + vault-server openapi specs

pkg/restapi/comparator/operation/operations.go, pkg/restapi/comparator/operation/operations_test.go, test/bdd/features/comparator_e2e_api.feature, test/bdd/pkg/comparator/comparator_steps.go
=> test: add Authorization test for comparator

cmd/confidential-storage-hub/docs/openapi.yaml, cmd/confidential-storage-hub/startcmd/start.go, pkg/restapi/csh/operation/compare.go, pkg/restapi/csh/operation/compare_test.go, pkg/restapi/csh/operation/entity.go, pkg/restapi/csh/operation/operations.go, pkg/restapi/csh/operation/operations_test.go, pkg/restapi/csh/operation/query_test.go, test/bdd/features/confidential-storage-hub_e2e_api.feature, test/bdd/fixtures/confidential-storage-hub/docker-compose.yml, test/bdd/pkg/chs/chs_steps.go, test/bdd/pkg/chs/user.go
=> feat: confidential-storage-hub - implement RefQuery

cmd/comparator-rest/docs/openapi.yaml
=> fix: comparator openapi - missing auth tokens

pkg/restapi/comparator/operation/operations.go
=> fix: add Content-Type json for return error

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/status/csl/csl.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/verifier/operation/operations.go, pkg/restapi/verifier/operation/operations_test.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go
=> chore: update aries-framework-go revision

go.mod, pkg/restapi/csh/operation/compare.go, pkg/restapi/csh/operation/compare_test.go, test/bdd/pkg/chs/chs_steps.go, test/bdd/pkg/chs/user.go
=> feat: confidential-storage-hub - support JSONPath

pkg/client/comparator/models/authorization.go, pkg/client/comparator/models/scope.go, pkg/restapi/comparator/controller_test.go, pkg/restapi/comparator/operation/authz.go, pkg/restapi/comparator/operation/models/authorization.go, pkg/restapi/comparator/operation/models/scope.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/comparator/operation/operations_test.go, scripts/check_license.sh, test/bdd/features/comparator_e2e_api.feature, test/bdd/pkg/comparator/comparator_steps.go
=> feat: implement comparator Authorization

pkg/restapi/comparator/operation/compare.go, pkg/restapi/comparator/operation/operations_test.go, test/bdd/features/comparator_e2e_api.feature, test/bdd/pkg/comparator/comparator_steps.go
=> feat: support AuthorizedQuery for comparator

test/bdd/pkg/vault/vault_steps.go
=> feat: Vault server - BDD decrypt.

test/bdd/features/comparator_e2e_api.feature, test/bdd/features/vault_server_e2e_api.feature, test/bdd/pkg/comparator/comparator_steps.go, test/bdd/pkg/vault/vault_steps.go
=> test: add negative test for compare

docs/build.md
=> docs: additional hosts file entry for BDD tests

.golangci.yml, cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/auth/zcapld/service.go, pkg/restapi/comparator/operation/authz.go, pkg/restapi/comparator/operation/compare.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/csh/operation/operations.go, pkg/restapi/csh/operation/operations_test.go, pkg/restapi/csh/operation/query.go, pkg/restapi/csh/operation/query_test.go, pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/chs/chs_steps.go, test/bdd/pkg/chs/user.go
=> refactor: Vault server - removes toDidURL usage

pkg/doc/vc/status/csl/csl.go, pkg/internal/common/utils/bitstring.go, pkg/internal/common/utils/bitstring_test.go, pkg/restapi/verifier/operation/operations.go, test/bdd/features/vc_e2e_api.feature, test/bdd/pkg/verifier/verifier_steps.go
=> fix: bitstring set position

test/bdd/pkg/vault/vault_steps.go
=> refactor: Vault BDD - removes sleep

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, go.mod, go.sum, pkg/restapi/issuer/operation/operations_test.go, test/bdd/fixtures/hub-kms/.env, test/bdd/fixtures/vault-server/.env, test/bdd/go.mod, test/bdd/go.sum
=> chore: update aries revision

pkg/doc/vc/status/csl/csl.go, pkg/doc/vc/status/csl/csl_test.go, pkg/internal/mock/edv/client.go, pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/openapi.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, test/bdd/pkg/vc/vc_steps.go
- https://github.com/w3c-ccg/vc-http-api/blob/e12828aec17011383db82bf6febc86824e691da6/docs/vc-http-api.yml#L70
=> refactor: update status endpoint to match vc-http api

cmd/common/storage.go, cmd/common/storage_test.go, cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/confidential-storage-hub/startcmd/start.go, cmd/confidential-storage-hub/startcmd/start_test.go, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/status/csl/csl_test.go, pkg/internal/mock/storage/store.go, pkg/restapi/csh/controller_test.go, pkg/restapi/csh/operation/compare.go, pkg/restapi/csh/operation/compare_test.go, pkg/restapi/csh/operation/operations.go, pkg/restapi/csh/operation/operations_test.go, pkg/restapi/csh/operation/query_test.go, test/bdd/go.mod
=> feat: Switch edge-core storage to Aries storage

test/bdd/features/comparator_e2e_api.feature, test/bdd/go.sum, test/bdd/pkg/comparator/comparator_steps.go
=> test: BDD test for comparator extraction of multiple documents

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> feat: generate key pair to support custom keytypes

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest AFG

pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/internal/common/did/common_test.go, pkg/restapi/internal/common/vcutil/vcutil.go, pkg/restapi/internal/common/vcutil/vcutil_test.go
=> feat: support for profiles with BBS signature type

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum
=> chore: Update aries-framework-go-ext storage commit versions

README.md, cmd/comparator-rest/README.md, cmd/confidential-storage-hub/README.md, cmd/vault-server/README.md
=> docs: add docs for CSH, Comparator, Vault Server

ci/version_var.sh
=> chore: bump to 0.1.7

docs/vc-rest/api_overview.md, docs/vc-rest/vc_interop_api_impl_status.md, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/verifier/operation/operations.go, pkg/restapi/verifier/operation/operations_test.go, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vc/vc_steps.go, test/bdd/pkg/verifier/verifier_steps.go
=> chore: change issuer and verifier endpoint path

pkg/restapi/issuer/operation/models.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go
=> feat: add CredentialStatus to IssueCredentialOptions

cmd/did-rest/go.mod, cmd/did-rest/go.sum, pkg/restapi/did/operation/operations.go, pkg/restapi/did/operation/operations_test.go
=> chore: use did:web aries

pkg/doc/vc/status/csl/csl.go, pkg/doc/vc/status/csl/csl_test.go, pkg/restapi/governance/operation/operations.go, pkg/restapi/governance/operation/operations_test.go, pkg/restapi/issuer/operation/openapi.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/verifier/operation/operations.go, pkg/restapi/verifier/operation/operations_test.go
=> fix: add vc status list for each profile

pkg/doc/vc/status/csl/csl.go
=> fix: add bbsBlsSignature2020Context for vc status list

cmd/comparator-rest/startcmd/start.go, cmd/confidential-storage-hub/startcmd/start.go, cmd/vault-server/startcmd/start.go, cmd/vc-rest/startcmd/start.go, pkg/did/creator.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/governance/operation/operations.go, pkg/restapi/holder/operation/operations.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/vault/client.go, test/bdd/fixtures/comparator-rest/docker-compose.yml, test/bdd/fixtures/confidential-storage-hub/docker-compose.yml, test/bdd/fixtures/vault-server/docker-compose.yml, test/bdd/fixtures/vc-rest/docker-compose.yml
=> feat: add did anchor origin parameter

cmd/did-rest/startcmd/start.go, pkg/restapi/did/controller.go, pkg/restapi/did/controller_test.go, pkg/restapi/did/operation/operations.go, pkg/restapi/did/operation/operations_test.go
=> feat: add orb vdr to did-rest

pkg/jsonld/contexts/booking-reference-v1.jsonld, pkg/jsonld/contexts/w3id-vaccination-v1.jsonld, pkg/jsonld/loader.go
Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>
=> chore: add contexts for supporting sandbox flows

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update afgo revision

pkg/restapi/comparator/operation/operations.go, pkg/restapi/csh/operation/operations.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/vault/client.go, test/bdd/fixtures/edv-rest/.env, test/bdd/fixtures/hub-kms/.env, test/bdd/fixtures/vault-server/.env, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vault/vault_steps.go
=> fix: orb vdr read

cmd/did-rest/startcmd/start.go, pkg/restapi/did/operation/operations.go
=> feat: add did domain to did rest

cmd/comparator-rest/startcmd/start.go, cmd/comparator-rest/startcmd/start_test.go, cmd/confidential-storage-hub/startcmd/start.go, cmd/confidential-storage-hub/startcmd/start_test.go, cmd/vault-server/startcmd/start.go, cmd/vault-server/startcmd/start_test.go, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, test/bdd/fixtures/comparator-rest/docker-compose.yml, test/bdd/fixtures/confidential-storage-hub/docker-compose.yml, test/bdd/fixtures/vault-server/docker-compose.yml, test/bdd/fixtures/vc-rest/docker-compose.yml
=> chore: add request token

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/crypto/crypto.go, pkg/restapi/comparator/operation/operations.go, pkg/restapi/internal/common/did/common.go, pkg/restapi/vault/client.go, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/issuer/issuer_steps.go, test/bdd/pkg/vault/vault_steps.go
=> feat: JsonWebKey2020 support

README.md
=> chore: Update build badge

scripts/check_lint.sh
=> fix: make check_lint.sh compatible for Mac

cmd/comparator-rest/go.mod, cmd/comparator-rest/go.sum, cmd/confidential-storage-hub/go.mod, cmd/confidential-storage-hub/go.sum, cmd/did-rest/go.mod, cmd/did-rest/go.sum, cmd/vault-server/go.mod, cmd/vault-server/go.sum, cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/internal/zcapldutil/invocation_action.go, pkg/internal/zcapldutil/invocation_action_test.go, pkg/restapi/csh/operation/query.go, pkg/restapi/csh/operation/query_test.go, pkg/restapi/vault/client.go, pkg/restapi/vault/client_test.go, pkg/restapi/verifier/operation/operations_test.go, scripts/generate_test_keys.sh, test/bdd/bddtests_test.go, test/bdd/fixtures/kms/.env, test/bdd/fixtures/kms/docker-compose.yml, test/bdd/fixtures/vault-server/.env, test/bdd/fixtures/vault-server/docker-compose.yml, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/chs/user.go, test/bdd/pkg/vault/vault_steps.go
=> chore: update Aries and KMS

docs/vcs/holder/README.md, docs/vcs/issuer/README.md, docs/vcs/verifier/README.md
Changed to use did:key example as it's independent of deployments/data loss.
=> docs: update vcs data samples with did:key signature

README.md
- change project name from edge-service to vcs
- update intro
=> docs: REAME update

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/doc/vc/crypto/crypto_test.go, pkg/doc/vc/status/csl/csl_test.go, pkg/restapi/governance/operation/operations_test.go, pkg/restapi/holder/operation/operations_test.go, pkg/restapi/issuer/operation/operations.go, pkg/restapi/issuer/operation/operations_test.go, pkg/restapi/verifier/operation/operations_test.go, test/bdd/go.mod, test/bdd/go.sum
=> feat: disable issuanceDate check for issue credential endpoint.

.github/workflows/build.yml
Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>
=> ci: add semantic commit check

Makefile, go.mod, pkg/storage/mongodb/client.go, pkg/storage/mongodb/verifierstore/profile_store.go, pkg/storage/mongodb/verifierstore/profile_store_test.go, pkg/verifier/profile.go, pkg/verifier/profile_test.go
=> feat: new service and storage for verifier profile.

pkg/did/creator.go, pkg/did/creator_test.go, pkg/doc/vc/validate.go, pkg/doc/vc/validate_test.go, pkg/issuer/profile.go, pkg/issuer/profile_test.go, pkg/storage/mongodb/issuerstore/profile_store.go, pkg/storage/mongodb/issuerstore/profile_store_test.go, pkg/storage/mongodb/util.go, pkg/storage/mongodb/util_test.go
=> feat: issuer profile

cmd/vc-rest/startcmd/start.go, pkg/did/creator.go, pkg/did/creator_test.go, pkg/doc/vc/crypto/crypto.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/storage/mongodb/issuerstore/profile_store.go, pkg/storage/mongodb/issuerstore/profile_store_test.go, test/bdd/bddtests_test.go, test/bdd/features/issuer_v1_api.feature, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/v1/issuer/issuer_steps.go, test/bdd/pkg/v1/issuer/model.go
=> feat: issuer profile bdd tests.

pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go, pkg/restapi/v1/verifier/testdata/create_profile_data.json, pkg/storage/mongodb/verifierstore/profile_store.go, pkg/storage/mongodb/verifierstore/profile_store_test.go, pkg/verifier/profile.go, test/bdd/bddtests_test.go, test/bdd/features/verifier_profile_api.feature, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/v1/verifier/models.go, test/bdd/pkg/v1/verifier/testdata/verifier_profile_create.json, test/bdd/pkg/v1/verifier/testdata/verifier_profile_created.json, test/bdd/pkg/v1/verifier/testdata/verifier_profile_update.json, test/bdd/pkg/v1/verifier/testdata/verifier_profile_updated.json, test/bdd/pkg/v1/verifier/verifer_steps.go
=> test: BDD tests for verifier profile management REST API

.github/workflows/build.yml, .github/workflows/interop.yml, Makefile, cmd/vc-rest/go.mod, docs/build.md, go.mod, test/bdd/go.mod
Signed-off-by: Rolson Quadras <rolson.quadras@avast.com>
=> ci: golang v1.19

.github/workflows/build.yml, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, test/bdd/fixtures/docker-compose.yml
=> fix: did web

pkg/issuer/profile.go, pkg/issuer/profile_test.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/storage/mongodb/issuerstore/profile_store.go, pkg/storage/mongodb/issuerstore/profile_store_test.go
=> chore: add signingDID to issuer profile

go.mod, go.sum, pkg/oidc/txmanager.go, pkg/oidc/txmanager_test.go, pkg/storage/redis/oidctxstore/tx_store.go, pkg/storage/redis/oidctxstore/tx_store_test.go
=> feat: oidc tx manager.

test/bdd/features/vc_v1_e2e_api.feature, test/bdd/fixtures/hydra-config/hydra_configure.sh, test/bdd/pkg/v1/vc/credential.go, test/bdd/pkg/v1/vc/issuer.go, test/bdd/pkg/v1/vc/vc_steps.go, test/bdd/pkg/v1/vc/verifier.go
=> test: fix authorization in BDD tests

pkg/restapi/v1/mw/api_key_auth.go, pkg/restapi/v1/mw/api_key_auth_test.go
=> fix: skip health check endpoint in auth middleware

pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/util.go, pkg/doc/vc/crypto/util_test.go, pkg/internal/common/diddoc/util.go, pkg/internal/common/diddoc/util_test.go, pkg/internal/testutil/credential.go, pkg/internal/testutil/presentation.go, pkg/service/verifycredential/testdata/university_degree.jsonld, pkg/service/verifycredential/verifycredential_service.go, pkg/service/verifycredential/verifycredential_service_test.go, pkg/service/verifypresentation/testdata/valid_vp.jsonld, pkg/service/verifypresentation/verifypresentation_service.go, pkg/service/verifypresentation/verifypresentation_service_test.go
VP verification service.
Linked issue: https://github.com/trustbloc/vcs/issues/757
=> feat: credential management - VP verification service

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, go.mod, go.sum, pkg/did/creator.go, pkg/kms/arieskms.go, pkg/kms/key/creator.go, pkg/kms/key/creator_test.go, test/bdd/features/vc_v1_e2e_api.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/go.sum, test/bdd/pkg/v1/issuer/issuer_steps.go
- Add tests for P-256, P-384 and P-256k1
closes #811
=> chore: add aws kms to bdd test

cmd/vc-rest/startcmd/configuration.go, cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go
=> chore: add https to vcs server

cmd/vc-rest/startcmd/configuration.go, cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start_test.go, component/profile/reader/file/creator.go, component/profile/reader/file/reader.go, pkg/doc/vc/crypto/crypto.go, test/bdd/fixtures/profile/profiles.json
=> feat: add did key support

cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, component/profile/reader/file/reader.go
=> chore: add ability to add custom flags

pkg/profile/api.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/service/oidc4vc/models.go, pkg/service/oidc4vc/oidc4vc_service.go, pkg/service/oidc4vc/oidc4vc_service_test.go
Spec is still in progress, and not all models have been defined yet. This functionality is going to be updated in the upcoming PRs along with other endpoints and as spec becomes more complete.
Closes #815
=> feat: initiate OIDC credential issuance for authorization code flow

test/bdd/features/vc_stress.feature, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/bddutil/workerpool.go, test/bdd/pkg/v1/vc/credential.go, test/bdd/pkg/v1/vc/stress_steps.go, test/bdd/pkg/v1/vc/vc_steps.go
=> chore: add vcs stress test

test/bdd/pkg/v1/vc/credential.go, test/bdd/pkg/v1/vc/vc_steps.go
=> chore: fix stress test race condition

.golangci.yml, component/event/bus_test.go, component/event/publisher_test.go, component/profile/reader/file/creator.go, component/profile/reader/file/reader.go, scripts/check_lint.sh, scripts/check_unit.sh
=> chore: enable lint and unit test for component folder

test/bdd/pkg/v1/oidc4vp/oidc4vp.go
=> fix: remove unused code from bdd test.

cmd/vc-rest/go.mod, cmd/vc-rest/startcmd/start.go, component/event/bus.go, component/event/bus_test.go, component/event/event.go, component/event/go.mod, component/event/go.sum, component/event/mocks/subscriber.gen.go, component/event/publisher_test.go, component/event/subscriber.go, component/event/subscriber_test.go, pkg/event/spi/spi.go, pkg/restapi/v1/issuer/controller.go, pkg/service/oidc4vp/oidc4vp_service.go, pkg/service/oidc4vp/oidc4vp_service_test.go
=> feat: initialize event

component/event/subscriber.go, pkg/event/spi/spi.go
- data field was showing as base64
=> fix: data field in event

cmd/vc-rest/startcmd/start.go, pkg/service/issuecredential/issuecredential_service.go, pkg/service/issuecredential/issuecredential_service_test.go, pkg/storage/mongodbprovider/common.go, pkg/storage/mongodbprovider/mongodbprovider_test.go, pkg/storage/mongodbprovider/vc.go
Ticket: https://butr.avast.com/browse/ID-3397
=> feat: Store VC after the issuing

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, go.mod, go.sum, pkg/restapi/v1/verifier/controller.go, pkg/service/oidc4vp/oidc4vp_service.go, pkg/service/verifypresentation/verifypresentation_service.go, test/bdd/features/oidc4vp_api.feature, test/bdd/fixtures/profile/profiles.json, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/v1/oidc4vp/wallet.go, test/bdd/pkg/v1/vc/vc_steps.go
=> feat: support jwt vc in verifaible presentation.

pkg/service/oidc4vc/errors.go, pkg/service/oidc4vc/models.go, pkg/service/oidc4vc/oidc4vc_service.go, pkg/service/oidc4vc/oidc4vc_service_test.go, pkg/storage/mongodb/oidc4vcstore/odc4_vc_store_test.go, pkg/storage/mongodb/oidc4vcstore/oidc4vc_store.go
Signed-off-by: Stas D <iqpirat@gmail.com>
=> feat: oidc4-vc store

cmd/vc-rest/startcmd/configuration.go, cmd/vc-rest/startcmd/params.go, component/profile/reader/file/creator.go, test/bdd/fixtures/did-resolver/config.json
=> chore: create did:ion long-form using uniregistrar

pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go
=> chore: disable id token validate

pkg/restapi/v1/verifier/controller.go
=> chore: fix log msg

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest aries

pkg/service/oidc4vp/oidc4vp_service.go
=> chore: add log msg

cmd/common/storage.go, cmd/vc-rest/go.mod, cmd/vc-rest/startcmd/configuration.go, cmd/vc-rest/startcmd/params.go, component/profile/reader/file/reader.go, go.mod, go.sum, internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, internal/pkg/tls/certpool.go, internal/pkg/tls/certpool_test.go, internal/pkg/utils/cmd/util.go, internal/pkg/utils/cmd/util_test.go, internal/pkg/utils/tls/util.go, internal/pkg/utils/tls/util_test.go, scripts/check_unit.sh, test/bdd/go.mod, test/bdd/pkg/context/context.go
=> refactor: remove did-core dependency

component/event/event.go, pkg/profile/api.go, pkg/service/oidc4vp/oidc4vp_service.go
=> feat: send event to webhook

component/event/event.go
=> chore: add tls config to send event

pkg/service/oidc4vp/oidc4vp_service.go
=> chore: add DisableSchemaValidation for PresentationDefinition match

pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go, test/bdd/pkg/v1/oidc4vp/oidc4vp.go
=> chore: enable id token validation

pkg/service/verifycredential/verifycredential_service.go, pkg/service/verifycredential/verifycredential_service_test.go, pkg/service/verifypresentation/verifypresentation_service.go, pkg/service/verifypresentation/verifypresentation_service_test.go, test/bdd/pkg/v1/oidc4vp/oidc4vp.go
=> chore: add WithStrictValidation for jsonld not jwt 

pkg/service/credentialstatus/credentialstatus_service.go, test/bdd/fixtures/profile/profiles.json
=> fix: did key for vc status list

component/oidc/fositemongo/access_token.go, component/oidc/fositemongo/access_token_test.go, component/oidc/fositemongo/assertions.go, component/oidc/fositemongo/assertions_test.go, component/oidc/fositemongo/auth_code.go, component/oidc/fositemongo/auth_code_test.go, component/oidc/fositemongo/client.go, component/oidc/fositemongo/client_test.go, component/oidc/fositemongo/common.go, component/oidc/fositemongo/common_test.go, component/oidc/fositemongo/fosite_mongo.go, component/oidc/fositemongo/fosite_mongo_test.go, component/oidc/fositemongo/par.go, component/oidc/fositemongo/par_test.go, component/oidc/fositemongo/pkce.go, component/oidc/fositemongo/pkce_test.go, component/oidc/fositemongo/refresh_token.go, component/oidc/fositemongo/refresh_token_test.go, component/oidc/fositemongo/store.go, component/oidc/fositemongo/store_test.go, component/oidc/fositemongo/types.go, component/oidc/fositemongo/types_test.go
=> feat: fosite mongo storage

pkg/restapi/v1/util/bind.go, pkg/service/verifycredential/revocation/revocation_service.go, test/bdd/pkg/v1/vc/credential.go
closes: https://github.com/trustbloc/vcs/issues/894
=> feat: ID-3489 Get rid of trailing newline sign in response

component/profile/reader/file/creator.go, component/profile/reader/file/reader.go
=> chore: add LinkedDomains svc to DID

pkg/service/didconfiguration/didconfiguration_service.go
=> fix: expried date in did config

pkg/service/didconfiguration/didconfiguration_service.go
=> chore: remove utc time for did config

pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/service/oidc4vc/errors.go, pkg/service/oidc4vc/models.go, pkg/service/oidc4vc/oidc4vc_service.go, pkg/service/oidc4vc/oidc4vc_service_test.go
=> refactor: oidc4vc initiate issuance api

component/profile/reader/file/creator.go
=> chore: add key to Authentication section in DID

cmd/vc-rest/startcmd/start.go, pkg/storage/mongodb/oidcnoncestore/tx_nonce_store.go, pkg/storage/mongodb/oidcnoncestore/tx_nonce_store_test.go
=> feat: set nonce to expire inside mongodb.

pkg/storage/mongodb/oidc4vcstore/oidc4vc_store.go, pkg/storage/mongodb/oidc4vcstore/oidc4vc_store_test.go
=> feat: oidc4vc store changes

pkg/restapi/v1/oidc4vc/controller.go, pkg/restapi/v1/oidc4vc/controller_e2e_flows_test.go
=> test: e2e test for OIDC4VC authorize handler

pkg/storage/mongodb/oidc4vcstore/oidc4vc_store.go, pkg/storage/mongodb/oidcnoncestore/tx_nonce_store.go, test/bdd/features/oidc4vp_stress.feature, test/bdd/pkg/v1/oidc4vp/oidc4vp.go, test/bdd/pkg/v1/oidc4vp/steps.go, test/bdd/pkg/v1/oidc4vp/stress_steps.go, test/bdd/pkg/v1/oidc4vp/vpflow_executor.go, test/bdd/pkg/v1/oidc4vp/wallet.go
=> feat: oidc4vp  stress test.

cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, go.mod, internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, pkg/doc/vc/crypto/crypto_test.go, pkg/kms/arieskms.go, pkg/kms/arieskms_test.go, pkg/kms/signer/arieskms.go, pkg/kms/signer/arieskms_test.go, pkg/observability/metrics/noop/provider.go, pkg/observability/metrics/noop/provider_test.go, pkg/observability/metrics/prometheus/handler.go, pkg/observability/metrics/prometheus/handler_test.go, pkg/observability/metrics/prometheus/provider.go, pkg/observability/metrics/prometheus/provider_test.go, pkg/observability/metrics/provider.go, pkg/restapi/common/common.go, pkg/service/credentialstatus/credentialstatus_service_test.go, pkg/service/issuecredential/issuecredential_service_test.go, pkg/service/oidc4vp/oidc4vp_service_test.go, scripts/check_lint.sh, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/prometheus-config/prometheus.yml, test/bdd/pkg/v1/oidc4vp/oidc4vp.go, test/bdd/pkg/vc-devapi/vc_devapi_steps.go
=> feat: metrics provider

cmd/vc-rest/startcmd/start.go, internal/pkg/log/fields.go, pkg/kms/arieskms.go, pkg/kms/signer/arieskms.go, pkg/observability/metrics/noop/provider.go, pkg/observability/metrics/noop/provider_test.go, pkg/observability/metrics/prometheus/provider.go, pkg/observability/metrics/prometheus/provider_test.go, pkg/observability/metrics/provider.go, pkg/restapi/v1/verifier/controller.go, pkg/service/oidc4vp/oidc4vp_service.go
add metrics for verifying authorization of VP and OIDCV4 VP verification as they are taking more than necessary time to execute
closes #930
=> chore: add auth verification metrics

internal/pkg/log/fields.go, internal/pkg/log/fields_test.go, pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go, pkg/service/oidc4vp/oidc4vp_service.go
=> feat: improved logs for oidc4vp.

cmd/vc-rest/startcmd/start.go
=> chore: enable metrics http handler

cmd/vc-rest/startcmd/start.go
=> fix: wrap prometheus handler call in echo server handler

test/bdd/bddtests_test.go, test/bdd/features/oidc4vc_api.feature, test/bdd/fixtures/hydra-config/hydra_configure.sh, test/bdd/fixtures/oathkeeper-config/rules/resource-server.json, test/bdd/fixtures/oauth-clients/clients.json, test/bdd/fixtures/profile/profiles.json, test/bdd/pkg/context/context.go, test/bdd/pkg/v1/oidc4vc/oidc4vc_steps.go
=> test: BDD test for token endpoint, refactor oidc4vc steps

pkg/doc/vc/signer.go, pkg/doc/vc/status.go, pkg/doc/vc/vcutil/vcutil.go, pkg/doc/vc/vcutil/vcutil_test.go, pkg/profile/api.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/service/credentialstatus/credentialstatus_service.go, pkg/service/credentialstatus/credentialstatus_service_test.go, pkg/service/credentialstatus/statusProcessor.go, pkg/service/credentialstatus/versions/common.go, pkg/service/credentialstatus/versions/revocationlist2020.go, pkg/service/credentialstatus/versions/revocationlist2020_test.go, pkg/service/credentialstatus/versions/revocationlist2021.go, pkg/service/credentialstatus/versions/revocationlist2021_test.go, pkg/service/credentialstatus/versions/statuslist2021.go, pkg/service/credentialstatus/versions/statuslist2021_test.go, pkg/service/issuecredential/issuecredential_service.go, pkg/service/issuecredential/issuecredential_service_test.go, pkg/service/verifycredential/verifycredential_service.go, pkg/service/verifycredential/verifycredential_service_test.go, test/bdd/fixtures/file-server/ld-contexts.json, test/bdd/fixtures/profile/profiles.json, test/bdd/pkg/bddutil/contexts/revocation-list-2021.jsonld, test/bdd/pkg/bddutil/util.go, test/bdd/pkg/v1/vc/credential.go
=> feat: Enable both variations of StatusList2021

pkg/service/credentialstatus/statustype/revocationlist2021.go, pkg/service/credentialstatus/statustype/revocationlist2021_test.go
=> feat: support float64 in GetStatusListIndex for revocation list 2021

images/vc-rest/Dockerfile
Remove RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
since it is causing failure.
=> chore: Fix docker image

test/bdd/bddtests_test.go, test/bdd/features/oidc4ci_api.feature, test/bdd/features/oidc4vc_api.feature, test/bdd/pkg/v1/oidc4ci/models.go, test/bdd/pkg/v1/oidc4ci/oidc4ci_steps.go, test/bdd/pkg/v1/oidc4ci/oidc4vc_pre_authorize_steps.go, test/bdd/pkg/v1/oidc4vc/oidc4ci.go, test/bdd/pkg/v1/oidc4vc/oidc4vp.go, test/bdd/pkg/v1/oidc4vc/steps.go, test/bdd/pkg/v1/oidc4vc/vpflow_executor.go, test/bdd/pkg/v1/oidc4vc/wallet.go
=> feat: openID4VC and openID4VP bddtest using wallet

cmd/vc-rest/startcmd/start.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/restapi/v1/issuer/testdata/sample_vc_university_degree.jsonld, pkg/restapi/v1/oidc4ci/controller.go, pkg/service/oidc4ci/models.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_test.go, scripts/generate_test_keys.sh, test/bdd/features/oidc4ci_api.feature, test/bdd/fixtures/profile/profiles.json, test/bdd/loginconsent/server.go, test/bdd/pkg/v1/oidc4ci/models.go, test/bdd/pkg/v1/oidc4ci/oidc4ci_steps.go
=> test: finalize bdd test for oidc4ci auth code flow

pkg/event/spi/spi.go, pkg/service/oidc4ci/models.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_exchange_code.go, pkg/service/oidc4ci/oidc4ci_service_exchange_code_test.go, pkg/service/oidc4vp/oidc4vp_service.go
and refactor issuer OIDC failure events to include the failing error
=> feat: support verifier OIDC failure events

component/wallet-cli/cmd/oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go
=> feat: oidc4ci auth code flow support in wallet cli (before login/consent)

component/wallet-cli/cmd/oidc4ci.go, component/wallet-cli/go.mod, component/wallet-cli/go.sum, component/wallet-cli/pkg/walletrunner/models.go, component/wallet-cli/pkg/walletrunner/vcprovider/provider.go, component/wallet-cli/pkg/walletrunner/wallet_runner.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, test/bdd/go.mod, test/bdd/go.sum
=> feat: oidc4ci auth code flow support in wallet cli for non-interactive mode

component/profile/reader/file/go.mod, go.mod, go.sum
=> chore: change profile reader module name

cmd/vc-rest/go.mod, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/oidc/fositemongo/go.mod, component/profile/reader/file/go.mod
=> chore: added VCS module version to components packages

component/wallet-cli/go.mod, component/wallet-cli/go.sum, test/bdd/go.mod
=> fix: go mod for wallet cli

pkg/storage/mongodb/ldstore/context_store.go, pkg/storage/mongodb/ldstore/context_store_test.go, pkg/storage/mongodb/ldstore/remote_provider_store.go, pkg/storage/mongodb/ldstore/remote_provider_store_test.go
=> feat: custom mongodb stores for ldcontext and remoteprovider

cmd/vc-rest/startcmd/configuration.go, cmd/vc-rest/startcmd/oauth_provider_test.go, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, pkg/ld/store_provider.go, pkg/ld/store_provider_test.go, pkg/storage/mongodb/client.go, pkg/storage/mongodb/cslstore/csl_store_test.go, pkg/storage/mongodb/ldstore/context_store_test.go, pkg/storage/mongodb/ldstore/remote_provider_store_test.go, pkg/storage/mongodb/oidc4cistatestore/oidc4vc_state_store_test.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store_test.go, pkg/storage/mongodb/oidc4vptxstore/oidc4vp_tx_store_test.go, pkg/storage/mongodb/oidcnoncestore/tx_nonce_store_test.go, pkg/storage/mongodb/requestobjectstore/request_object_store_test.go, pkg/storage/mongodb/vcstore/vc_store_test.go
=> chore: use custom mongodb stores for ldcontext and remoteprovider

pkg/storage/mongodb/client.go
=> fix: tls config for mongodb tls

cmd/vc-rest/startcmd/oauth_provider_test.go, cmd/vc-rest/startcmd/start.go, pkg/ld/store_provider_test.go, pkg/storage/mongodb/client.go, pkg/storage/mongodb/cslstore/csl_store_test.go, pkg/storage/mongodb/ldstore/context_store_test.go, pkg/storage/mongodb/ldstore/remote_provider_store_test.go, pkg/storage/mongodb/oidc4cistatestore/oidc4vc_state_store_test.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store_test.go, pkg/storage/mongodb/oidc4vptxstore/oidc4vp_tx_store_test.go, pkg/storage/mongodb/oidcnoncestore/tx_nonce_store_test.go, pkg/storage/mongodb/requestobjectstore/request_object_store_test.go, pkg/storage/mongodb/vcstore/vc_store_test.go
=> chore: remove tlsconfig from mongodb

component/oidc/fositemongo/common.go, component/wallet-cli/cmd/oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, pkg/restapi/v1/oidc4ci/controller.go
=> fix: updates to wallet cli to support oidc4ci auth code flow

component/wallet-cli/README.md
=> chore: updated wallet-cli docs

.github/workflows/build.yml, .github/workflows/publish.yaml
=> fix: publish job

component/wallet-cli/README.md
=> chore: update OIDC4CI version in wallet CLI readme

component/wallet-cli/pkg/walletrunner/wallet_runner.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci_pre_auth.go
=> feat: support for login with a browser for oidc4vci auth code flow

component/wallet-cli/README.md, component/wallet-cli/go.mod, component/wallet-cli/go.sum, component/wallet-cli/pkg/walletrunner/wallet.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go, test/bdd/go.mod, test/bdd/go.sum
=> feat: improve wallet-cli support of oidc4vci auth code flow

pkg/restapi/v1/oidc4ci/controller.go, pkg/restapi/v1/oidc4ci/controller_e2e_flows_test.go, pkg/restapi/v1/oidc4ci/controller_test.go, test/bdd/fixtures/oauth-clients/clients.json, test/bdd/pkg/v1/oidc4ci/oidc4ci_steps.go, test/bdd/pkg/v1/oidc4ci/oidc4vc_pre_authorize_steps.go, test/bdd/pkg/v1/oidc4vc/oidc4ci.go
=> fix: redirect uri in pre-auth code flow

component/wallet-cli/pkg/walletrunner/models.go, component/wallet-cli/pkg/walletrunner/vcprovider/provider.go, component/wallet-cli/pkg/walletrunner/wallet.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go
=> fix: wallet cli signing header

pkg/restapi/v1/verifier/controller.go
=> chore: change log msg

component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go
=> fix: wallet cli interop issues

pkg/profile/api.go, pkg/service/issuecredential/issuecredential_service.go
=> chore: add flag to disable status list

pkg/service/verifycredential/verifycredential_service.go
=> chore: add error msg if status list is missing

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/configuration.go, cmd/vc-rest/startcmd/start_test.go, component/credentialstatus/credentialstatus_service.go, component/profile/reader/file/creator.go, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/profile/reader/file/reader.go, pkg/doc/vc/crypto/crypto.go, test/bdd/fixtures/profile/profiles.json
=> chore: add support to did:jwk

pkg/restapi/v1/verifier/controller.go
=> chore: check header for AuthorizationResponse

component/credentialstatus/credentialstatus_service.go, component/credentialstatus/credentialstatus_service_test.go, pkg/service/issuecredential/issuecredential_service.go, pkg/service/issuecredential/issuecredential_service_test.go
=> chore: renamed StatusID to StatusListEntry in credentialstatus service

pkg/storage/mongodb/vcstatusstore/vc_status_store.go
=> chore: reduce typedID memory usage in DB

pkg/kms/arieskms.go
=> chore: add key alias for creating aws key

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest kms

cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, pkg/kms/arieskms.go, pkg/kms/kms.go, test/bdd/fixtures/docker-compose.yml
=> chore: add VC_REST_DEFAULT_KMS_ALIAS_PREFIX

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, go.mod, go.sum, pkg/kms/arieskms.go, pkg/kms/kms.go, test/bdd/go.mod, test/bdd/go.sum
=> chore: add stscreds for aws client

pkg/kms/arieskms.go
=> fix: aws config

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: update to latest sdk

cmd/vc-rest/startcmd/start.go, test/bdd/fixtures/krakend-config/settings/endpoint.json
=> fix: .well-known/openid-configuration endpoint

cmd/vc-rest/startcmd/start.go, component/wallet-cli/pkg/walletrunner/vcprovider/vcs.go, component/wallet-cli/pkg/walletrunner/wallet_runner.go
=> chore: update RedirectURL

pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, test/bdd/features/oidc4ci_api.feature, test/bdd/fixtures/profile/profiles.json, test/bdd/pkg/v1/oidc4ci/oidc4vc_pre_authorize_steps.go
=> feat: make oidc config optional for pre-authorize

go.sum, pkg/service/oidc4ci/models.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, pkg/service/oidc4vp/oidc4vp_service.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store.go
=> chore: send profile id and org id in event

cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, component/wallet-cli/pkg/credentialoffer/credentialoffer.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci_pre_auth.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go, pkg/storage/s3/credentialoffer/credential_offer_store.go, pkg/storage/s3/credentialoffer/credential_offer_store_test.go, test/bdd/pkg/v1/oidc4ci/oidc4ci_steps.go, test/bdd/pkg/v1/oidc4ci/oidc4vc_pre_authorize_steps.go, test/bdd/pkg/v1/oidc4vc/oidc4ci.go
=> feat: add support for credential offer uri

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/wallet-cli/go.mod, component/wallet-cli/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
Enables JSON logger encoding.
Signed-off-by: Bob Stasyszyn <Bob.Stasyszyn@securekey.com>
=> chore: Bump version of logutil-go

go.sum, pkg/profile/api.go, pkg/service/oidc4ci/models.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go, pkg/service/oidc4ci/oidc4ci_service_test.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store_test.go
=> fix: Issuer value

cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, pkg/service/oidc4ci/models.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go, pkg/service/oidc4ci/oidc4ci_service_test.go, pkg/storage/mongodb/claimdatastore/claim_data_store.go, pkg/storage/mongodb/claimdatastore/claim_data_store_test.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store_test.go
=> feat: user claims store with ttl

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/wallet-cli/go.mod, component/wallet-cli/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> chore: Update AFGO

docs/build.md
Added new aliases to /etc/hosts
=> chore: Update BDD doc

pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_test.go, pkg/storage/mongodb/claimdatastore/claim_data_store.go, pkg/storage/mongodb/claimdatastore/claim_data_store_test.go, pkg/storage/mongodb/ldstore/context_store_test.go, test/bdd/features/oidc4ci_api.feature, test/bdd/pkg/v1/oidc4ci/credentials.go, test/bdd/pkg/v1/oidc4ci/oidc4vc_pre_authorize_steps.go
=> test: update bdd test to verify claims deletion

cmd/vc-rest/startcmd/start.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/service/oidc4ci/models.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_exchange_code.go, pkg/service/oidc4ci/oidc4ci_service_exchange_code_test.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store.go, pkg/storage/mongodb/oidc4cistore/oidc4vc_store_test.go
=> refactor: remove client id and secret from transaction data

go.mod, pkg/storage/s3/requestobjectstore/request_object_store.go
=> feat: add s3 logs

cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, pkg/storage/s3/requestobjectstore/request_object_store.go, pkg/storage/s3/requestobjectstore/request_object_store_test.go
=> chore: add REQUEST_OBJECT_REPOSITORY_S3_HOSTNAME

pkg/storage/s3/requestobjectstore/request_object_store.go
=> fix: s3 hostname

go.mod, pkg/storage/s3/requestobjectstore/request_object_store.go
This reverts commit c8468d1a234e7c8c46bf4dc81060d0db1e8b8ee5.
=> feat: revert add s3 logs

pkg/storage/s3/requestobjectstore/request_object_store.go, pkg/storage/s3/requestobjectstore/request_object_store_test.go
=> fix: request uri s3

pkg/service/oidc4vp/txmanager.go
=> chore: add logs to check why tx ID not found

pkg/service/oidc4vp/txmanager.go, pkg/service/oidc4vp/txmanager_test.go, pkg/storage/mongodb/oidc4vptxstore/oidc4vp_tx_store.go, pkg/storage/mongodb/oidc4vptxstore/oidc4vp_tx_store_test.go
=> fix: get create tx in vp flow

pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go
=> fix: crash when returned profile is nil

component/credentialstatus/credentialstatus_service.go, component/credentialstatus/credentialstatus_service_test.go, pkg/service/credentialstatus/store.go, pkg/service/credentialstatus/types.go, pkg/storage/mongodb/cslstore/csl_store.go, pkg/storage/mongodb/cslstore/csl_store_test.go, pkg/storage/s3/cslstore/csl_store.go, pkg/storage/s3/cslstore/csl_store_test.go
=> chore: fix CSL S3 URL response

pkg/storage/s3/cslstore/csl_store.go
=> fix: csl store s3 

component/wallet-cli/pkg/walletrunner/wallet.go, component/wallet-cli/pkg/walletrunner/wallet_runner.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci_pre_auth.go, test/bdd/features/oidc4vc_stress.feature, test/bdd/pkg/v1/oidc4vc/steps.go, test/bdd/pkg/v1/oidc4vc/stress_steps.go, test/bdd/pkg/v1/oidc4vc/stress_test_case.go
=> test: stress test for pre-auth code flow and presentation

component/credentialstatus/credentialstatus_service.go, pkg/doc/vc/crypto/crypto.go
=> fix: did key creator

pkg/doc/vc/crypto/crypto.go, pkg/storage/mongodb/ldstore/context_store.go, pkg/storage/mongodb/ldstore/context_store_test.go
=> fix: store context

Makefile, component/wallet-cli/pkg/walletrunner/wallet_runner.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci_pre_auth.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go, test/bdd/features/oidc4vc_stress.feature, test/bdd/pkg/v1/oidc4vc/steps.go, test/bdd/pkg/v1/oidc4vc/stress_steps.go, test/bdd/pkg/v1/oidc4vc/stress_test_case.go
=> test: add more granular metrics for oidc4vc stress test

pkg/service/oidc4vp/oidc4vp_service.go, pkg/service/oidc4vp/oidc4vp_service_test.go
Signed-off-by: Anton Biriukov <anton.biriukov@avast.com>
=> fix: updated error message in checkVCSubject func

component/wallet-cli/go.mod, component/wallet-cli/go.sum, component/wallet-cli/internal/vdrutil/vdrutil.go, component/wallet-cli/pkg/walletrunner/wallet.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go, test/bdd/go.mod, test/bdd/go.sum
=> chore: support did key and did jwk in wallet CLI

component/wallet-cli/cmd/oidc4vp.go, component/wallet-cli/go.mod, component/wallet-cli/go.sum
=> fix: wallet cli qr

cmd/vc-rest/startcmd/params.go, pkg/service/oidc4vp/txmanager.go, pkg/service/oidc4vp/txmanager_test.go, pkg/storage/mongodb/oidc4vpclaimsstore/oidc4vp_claims_store.go, pkg/storage/mongodb/oidc4vpclaimsstore/oidc4vp_claims_store_test.go, test/bdd/features/oidc4vp_api.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/pkg/common/common_steps.go, test/bdd/pkg/v1/oidc4vp/oidc4vp.go, test/bdd/pkg/v1/oidc4vp/steps.go, test/bdd/pkg/v1/oidc4vp/stress_steps.go, test/bdd/pkg/v1/oidc4vp/vpflow_executor.go
Expire "receivedClaims" BDD test
Closes #1113
=> chore: Expire "receivedClaims" BDD test

component/wallet-cli/cmd/oidc4ci.go, component/wallet-cli/go.mod, component/wallet-cli/go.sum, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go, test/bdd/pkg/v1/oidc4ci/oidc4vc_pre_authorize_steps.go
=> feat: change issuance schema for oidc4ci

cmd/vc-rest/startcmd/start.go
=> fix: set loglevel

component/wallet-cli/README.md, component/wallet-cli/cmd/oidc4ci.go, component/wallet-cli/cmd/oidc4vp.go, component/wallet-cli/pkg/walletrunner/vcprovider/vcs.go, docs/v1/common.yaml, pkg/doc/verifiable/format.go, pkg/restapi/v1/common/common.go, pkg/restapi/v1/common/common_test.go, pkg/restapi/v1/common/openapi.gen.go, pkg/restapi/v1/oidc4ci/controller_e2e_flows_test.go, pkg/restapi/v1/oidc4ci/controller_test.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go, test/bdd/bddtests_test.go, test/bdd/features/oidc4vc_api.feature, test/bdd/features/oidc4vp_api.feature, test/bdd/features/oidc4vp_stress.feature, test/bdd/features/vc_v1_e2e_api.feature, test/bdd/fixtures/docker-compose.yml, test/bdd/fixtures/profile/profiles.json, test/bdd/pkg/v1/oidc4ci/credentials.go, test/bdd/pkg/v1/oidc4ci/oidc4ci_steps.go, test/bdd/pkg/v1/oidc4vc/oidc4ci.go, test/bdd/pkg/v1/vc/credential.go
=> feat: change format

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/wallet-cli/go.mod, component/wallet-cli/go.sum, go.mod, go.sum, test/bdd/go.mod, test/bdd/go.sum
=> feat: update aries

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/wallet-cli/go.mod, component/wallet-cli/go.sum, go.mod, go.sum, pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go, pkg/service/oidc4vp/oidc4vp_service.go, pkg/service/oidc4vp/oidc4vp_service_test.go, test/bdd/go.mod, test/bdd/go.sum
Verifier should be able to verify multiple presentations in CheckAuthorizationResponse.
=> feat: Verify Multiple Presentations in CheckAuthorizationResponse

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/wallet-cli/go.mod, component/wallet-cli/go.sum, go.mod, go.sum, pkg/service/oidc4vp/oidc4vp_service.go, pkg/service/oidc4vp/oidc4vp_service_test.go, test/bdd/features/oidc4_multi_vp_api.feature, test/bdd/features/oidc4vp_api.feature, test/bdd/features/oidc4vp_stress.feature, test/bdd/features/vc_dev_api.feature, test/bdd/fixtures/profile/profiles.json, test/bdd/go.mod, test/bdd/go.sum, test/bdd/pkg/context/context.go, test/bdd/pkg/v1/oidc4vc/wallet.go, test/bdd/pkg/v1/oidc4vp/oidc4vp.go, test/bdd/pkg/v1/oidc4vp/steps.go, test/bdd/pkg/v1/oidc4vp/vpflow_executor.go, test/bdd/pkg/v1/oidc4vp/wallet.go, test/bdd/pkg/v1/vc/credential.go, test/bdd/pkg/v1/vc/stress_steps.go, test/bdd/pkg/v1/vc/vc_steps.go
BDD Test for Multiple Presentations
Closes #1143
=> test: BDD Test for Multiple Presentations

cmd/common/common.go, cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, pkg/restapi/v1/logapi/controller.go, pkg/restapi/v1/logapi/controller_test.go, pkg/restapi/v1/mw/api_key_auth.go, pkg/restapi/v1/mw/api_key_auth_test.go, test/bdd/features/vc_log_api.feature, test/bdd/pkg/common/common_steps.go
Add rest endpoint to configure log levels
Closes #1186
=> feat: Configure log levels

cmd/vc-rest/startcmd/params.go, cmd/vc-rest/startcmd/start.go, cmd/vc-rest/startcmd/start_test.go, test/bdd/fixtures/docker-compose.yml
Add http client timeout(s) start-up parameters.
Closes #1198
=> chore: Add http client timeouts (start-up parameters)

pkg/cslmanager/cslmanager.go
=> chore: Add mutex to CSL Manager

test/bdd/features/vc_v1_e2e_api.feature
Add two VC revocations pre profile test
=> chore: Add two VC revocations per profile test

pkg/event/spi/spi.go
Update event definition.
Closes #1256
=> chore: update event definition

pkg/observability/tracing/wrappers/oidc4vp/oidc4vp_wrapper.go, pkg/observability/tracing/wrappers/oidc4vp/oidc4vp_wrapper_test.go, pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go, pkg/service/oidc4vp/api.go, pkg/service/oidc4vp/oidc4vp_service.go, pkg/service/oidc4vp/oidc4vp_service_test.go, pkg/service/oidc4vp/txmanager.go, pkg/service/oidc4vp/txmanager_test.go, pkg/storage/mongodb/oidc4vpclaimsstore/oidc4vp_claims_store.go, pkg/storage/mongodb/oidc4vpclaimsstore/oidc4vp_claims_store_test.go, pkg/storage/redis/oidc4vpclaimsstore/oidc4vp_claims_store.go, pkg/storage/redis/oidc4vpclaimsstore/oidc4vp_claims_store_test.go, test/bdd/features/oidc4vp_api.feature, test/bdd/pkg/v1/oidc4vp/oidc4vp.go, test/bdd/pkg/v1/oidc4vp/steps.go
Delete received claims upon retrieval.
Closes #1263
=> feat: delete received claims

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/wallet-cli/go.mod, component/wallet-cli/go.sum, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go, go.mod, go.sum, pkg/service/verifypresentation/verifypresentation_service.go, pkg/service/verifypresentation/verifypresentation_service_test.go, test/bdd/go.mod, test/bdd/go.sum, test/stress/go.mod, test/stress/go.sum
at the time of validatePresentationProof we already have parsed and verified presentation.
https://github.com/trustbloc/vcs/blob/main/pkg/restapi/v1/verifier/controller.go#L475
https://github.com/trustbloc/vcs/blob/main/pkg/restapi/v1/verifier/controller.go#L267
This two functions are using validatePresentationProof . there is no reason trying to parse it one more time as we sure that its valid
=> perf: improve vp flow

component/profile/reader/file/reader.go
Signed-off-by: Anton Biriukov <anton.biriukov@gendigital.com>
=> feat: added difDidOrigin to issuer profile did creation

pkg/restapi/v1/verifier/controller.go
=> Revert "chore: add vp token log"

component/wallet-cli/cmd/oidc4vp.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vp.go, pkg/doc/verifiable/signaturetype.go, pkg/doc/verifiable/signaturetype_test.go, pkg/internal/testutil/jwt.go, pkg/internal/testutil/presentation.go, pkg/kms/arieskms.go, pkg/restapi/v1/verifier/controller.go, pkg/restapi/v1/verifier/controller_test.go, pkg/service/oidc4vp/api.go, pkg/service/oidc4vp/oidc4vp_service.go, pkg/service/oidc4vp/oidc4vp_service_test.go, pkg/service/verifypresentation/verifypresentation_service_test.go, test/bdd/features/oidc4vc_api.feature, test/bdd/fixtures/profile/profiles.json, test/bdd/pkg/v1/oidc4vc/oidc4vp.go, test/bdd/pkg/v1/oidc4vc/steps.go, test/stress/pkg/stress/stress_test_case.go
Related doc: https://openid.net/specs/openid-connect-4-verifiable-presentations-1_0-ID1.html#name-introduction
=> feat: VCS Verifier - Enforce Intended format rule during OIDC4VP

component/profile/reader/file/creator.go
=> Revert "chore: update linked domain id in profile creator"

component/wallet-cli/cmd/oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, pkg/restapi/v1/oidc4ci/controller.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_test.go, pkg/service/oidc4ci/regex.go, test/bdd/fixtures/oauth-clients/clients.json, test/bdd/pkg/v1/oidc4vc/oidc4ci.go
=> feat: use issuer_state for wallet-flow

component/profile/reader/file/internal.go, component/profile/reader/file/reader.go, pkg/profile/api.go, pkg/service/verifypresentation/verifypresentation_service.go, pkg/service/verifypresentation/verifypresentation_service_test.go, scripts/check_lint.sh, test/bdd/features/oidc4vc_api.feature, test/bdd/fixtures/profile/profiles.json
=> feat: add trust list support

Makefile
- Update docker image for the cli bin build https://github.com/trustbloc/vcs/actions/runs/5969419726/job/16195587229
=> ci: fix publish build

component/profile/reader/file/go.mod, component/profile/reader/file/reader.go, component/profile/reader/file/reader_test.go, go.mod, internal/logfields/fields.go, internal/logfields/fields_test.go, pkg/internal/common/jsonschema/jsonschema.go, pkg/internal/common/jsonschema/jsonschema_test.go, pkg/internal/common/jsonschema/testdata/invalid.schema.json, pkg/internal/common/jsonschema/testdata/sample_invalid_university_degree.jsonld, pkg/internal/common/jsonschema/testdata/sample_university_degree.jsonld, pkg/internal/common/jsonschema/testdata/universitydegree.schema.json, pkg/profile/api.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/issuer/controller_test.go, scripts/check_unit.sh, test/bdd/features/oidc4vc_api.feature
Implemented a JSON schema validator cache so that the JSON schema is compiled once and reused.
=> feat: Cache JSON schema validators

cmd/vc-rest/startcmd/start.go, component/wallet-cli/pkg/credentialoffer/credentialoffer.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4ci_pre_auth.go, pkg/doc/vc/crypto/crypto.go, pkg/doc/vc/crypto/crypto_test.go, pkg/profile/api.go, pkg/restapi/v1/issuer/controller.go, pkg/restapi/v1/util/bind.go, pkg/service/oidc4ci/api.go, pkg/service/oidc4ci/oidc4ci_service.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance.go, pkg/service/oidc4ci/oidc4ci_service_initiate_issuance_test.go, pkg/storage/s3/credentialoffer/credential_offer_store.go, pkg/storage/s3/credentialoffer/credential_offer_store_test.go, test/bdd/fixtures/profile/profiles.json
Response dump:
```
HTTP/1.1 200 OK
Content-Length: 1011
Content-Type: application/jwt
Date: Thu, 07 Sep 2023 18:32:41 GMT
Vary: Origin
X-Krakend: Version 2.1.3
X-Krakend-Completed: false
{
"offer_credential_url": "openid-credential-offer://?credential_offer=eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDprZXk6ekRuYWV3R25LZ0F4OVU3SlNBZ3FXQVZVdjJlY01HenMxRVdRa3pmMXMxTlJXZWd2bSN6RG5hZXdHbktnQXg5VTdKU0FncVdBVlV2MmVjTUd6czFFV1FremYxczFOUldlZ3ZtIn0.eyJjcmVkZW50aWFsX29mZmVyIjp7ImNyZWRlbnRpYWxfaXNzdWVyIjoiaHR0cHM6Ly9hcGktZ2F0ZXdheS50cnVzdGJsb2MubG9jYWw6NTU2Ni9pc3N1ZXIvaV9teXByb2ZpbGVfY210cl9wMjU2X2xkcC92MS4wIiwiY3JlZGVudGlhbHMiOlt7ImZvcm1hdCI6ImxkcF92YyIsInR5cGVzIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiQ3J1ZGVQcm9kdWN0Q3JlZGVudGlhbCJdfV0sImdyYW50cyI6eyJhdXRob3JpemF0aW9uX2NvZGUiOnsiaXNzdWVyX3N0YXRlIjoiODM0MmZhZmYtZj …
```
=> feat: Signed credential offer for Issuance

component/wallet-cli/README.md, component/wallet-cli/cmd/create_wallet_cmd.go, component/wallet-cli/pkg/oidc4vci/oidc4vci_flow.go, component/wallet-cli/pkg/oidc4vp/oidc4vp_flow.go, component/wallet-cli/pkg/wellknown/wellknown.go
This PR fixes support for did:jwk method in wallet cli and improves logging output.
=> fix: support for did:jwk in wallet cli

component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vci.go, component/wallet-cli/pkg/walletrunner/wallet_runner_oidc4vci_pre_auth.go, test/bdd/features/oidc4vc_api.feature, test/bdd/pkg/v1/oidc4vc/oidc4ci.go, test/bdd/pkg/v1/oidc4vc/steps.go, test/stress/pkg/stress/stress_test_case.go
- invalid JWT kid header
- invalid signature
- invalid nonce in /credential req
=> feat: extend BDD tests

component/event/event.go
All event types are now published.
=> feat: Don't filter on event type when publishing event

component/wallet-cli/pkg/oidc4vci/oidc4vci_flow.go, component/wallet-cli/pkg/oidc4vp/oidc4vp_flow.go
Allow to substitute the default trust-registry client.
=> feat: Add trust-registry option in wallet-cli flows

cmd/vc-rest/go.mod, cmd/vc-rest/go.sum, component/credentialstatus/go.mod, component/credentialstatus/go.sum, component/event/go.mod, component/event/go.sum, component/profile/reader/file/go.mod, component/profile/reader/file/go.sum, component/wallet-cli/go.mod, component/wallet-cli/go.sum, go.mod, go.sum, pkg/service/oidc4vp/txmanager_test.go, test/bdd/attestation/go.mod, test/bdd/attestation/go.sum, test/bdd/features/oidc4vc_api.feature, test/bdd/fixtures/profile/profiles.json, test/bdd/go.mod, test/bdd/go.sum, test/stress/go.mod, test/stress/go.sum
Also added VC DM 2.0 pre-auth BDD tests.
=> feat: Add support for VC DM 2.0 enveloped credential/presentation

cmd/vc-rest/startcmd/start.go, component/credentialstatus/credentialstatus_service.go, component/credentialstatus/credentialstatus_service_test.go, component/event/bus.go, component/event/event.go, pkg/service/credentialstatus/cslservice/cslservice.go, pkg/service/credentialstatus/cslservice/cslservice_test.go, pkg/service/credentialstatus/eventhandler/eventhandler_service.go, pkg/service/credentialstatus/eventhandler/eventhandler_service_test.go
Extract the code that retrieves/signs CSLs into a separate service.
=> refactor: Refactor CSL event handler
